### ISSUE TITLE
Validation errors thrown when using async/href loading of templates

### ISSUE THREAD

**Issue by vanderstaaij** [twigjs/twig.js#104]
Hi,

I love Twig.js and have been working for a while now succesfully with it. However, I'm getting these validation errors now in my Firefox error console after loading templates using href/async. My app runs fine however, but still I would like to fix these errors. They are for example:

Error: junk after document element
Error: mismatched tag. Expected: </expected tag>
Error: no element found

All errors are followed by a reference to the .twig template loaded, the line number and a snippet of the template.

The errors look like some kind of XML parsing error, but I'm guessing that XML parsing/validating at that point is not really necessary as it is to be processed by Twig.js. I know the templates won't validate because of the {{ }} and {% %} tags in them.

Any suggestions on how to fix this, except for enclosing templates in script tags?

I'm using Firefox 22.0 for development, with Firebug 1.11.4, Web developer 1.2.5 add-ons. HTML5 is used on the web app I'm using.

Regards,
Eric

**Comment by dave-irvine** [comment]
No update in 30 days, closing.

**Comment by lightbyte** [comment]
I didn't know how to set the content-type in the request because that request is done inside twig engine, so I **renamed template files**, so instead "template.twig" would be "template.twig.html", the extension wouldn't be unknown and the XHR would use default content-type for that extension.
