### ISSUE TITLE
AMD and CommonJS doesn't get the same Twig object as the window global.

### ISSUE THREAD

**Issue by csimi** [twigjs/twig.js#131]
AMD and CommonJS seems to get the Twig.exports object, which doesn't contain critical functions necessary for plugin development like Twig.tokenize and other internal things.
Thankfully AMD users in the browser can fall back to the window global as this is set regardless of the presence of an AMD loader but Node.js sandboxes the module so this workaround is not available.
Is this intentional?

**Comment by dbashford** [comment]
:+1: 

This tripped me up a bit.  If dealing with precompiled templates, the `render` function makes reference to things like `Twig.parse` which are not available via AMD.

**Comment by evgenius** [comment]
@dbashford Thanks for pinging. I'll take a look on the weekend.

**Comment by willrowe** [comment]
Things will be moving towards modules, so there is no plan to change the default exports before that.
