### ISSUE TITLE
Trying to compile several templates in a directory throws a TypeError

### ISSUE THREAD

**Issue by royriojas** [twigjs/twig.js#142]
Running:

```
 twigjs templates/ --output out
```

Those are the details of the error

```
 forEachAsync(files, filesHandler).then(postFilesHandler);
          ^
TypeError: object is not a function
    at readFiles (node_modules/twig/node_modules/walk/walk.js:93:11)
    at readdirHandler (node_modules/twig/node_modules/walk/walk.js:98:9)
    at Object.oncomplete (fs.js:107:15)
```

It seems that `forEachAsync` which is used inside `walk` has been updated and the API has changed. The same is true for `sequence`.

At least for now you should consider use `npm-shrinkwrap`, a better solution will be to update to the latest dependency and use a specific version in your `package.json` not using `>=` anymore, which will break in case of API update of any dependency.

**Comment by willrowe** [comment]
A lock file is now being used. I'm not sure if the original issue has been resolved in more recent versions, but please re-open if it needs to be revisited.
