### ISSUE TITLE
date filter does not work properly

### ISSUE THREAD

**Issue by LabsterLtd** [twigjs/twig.js#147]
{{ 1394911763 | date }} prints Thu Jan 01 1970 04:00:00 GMT+0400 (MSK)

**Comment by evgenius** [comment]
{{ 1394911763 | date }} doesn't work at all now. I opened #227

**Comment by plepe** [comment]
Interestingly the behaviour depends on the browser. The following code:
```twig
{{ "2015-04-15T20:33:59+02:00"|date("d.m.Y") }}
```
prints the following results:
* "15.04.2015" on Chromium 41, Chrome (Android), Android Browser
* "01.01.1970" on Firefox 37, GNOME Webbrowser 3.10.3, Opera 12, Safari 5.1, IE8

**Comment by evgenius** [comment]
Thanks @plepe, I'll try to fix it soon.

**Comment by dave-irvine** [comment]
This is working for me now, so assuming it has been fixed somewhere along the way.

**Comment by plepe** [comment]
Oh yes, I knew there was still an open issue. I fixed it myself in #276 :)
