### ISSUE TITLE
Multiple extensions per one parent template

### ISSUE THREAD

**Issue by jeserkin** [twigjs/twig.js#153]
I was playing around with `twig.js` and found out, that multiple extensions don't work as I imagened.

Tried the following:
```javascript
var twig = Twig.twig;

twig({
    id: 'layout',
    data: '{% block templateOne %}First template here{% endblock %}{% block templateTwo %}Second template here{% endblock %}'
});

twig({
    allowInlineIncludes: true,
    data: '{% extends layout %}{% block templateOne %}First template rendered!{% endblock %}'
});

var template = twig({
    allowInlineIncludes: true,
    data: '{% extends layout %}{% block templateTwo %} Second template rendered!{% endblock %}'
});
```

I would expect to get
```javascript
template.render({}).should.equal("First template rendered! Second template rendered!");
```

What I'm getting is `Second template rendered!`

**Comment by dave-irvine** [comment]
Hi @jeserkin,

I don't think you can call twig like this. Try putting all your templates into one string and then call `twig()` with that data object.

I believe each time you call `twig()` it resets its stack, so calling it several times will not work.

**Comment by jeserkin** [comment]
Thanks, but I'm not using it anymore. Post is since 2014 :)
