### ISSUE TITLE
Defined test not working properly on object properties

### ISSUE THREAD

**Issue by targos** [twigjs/twig.js#160]
Unlike the original version of twig, a condition like "{% if foo.bar is defined %}" is always true if foo exists.
The reason is that if "foo" is defined and it has no "bar" property, then the value "null" is sent to the "defined" test. Null is not considered undefined so the test always returns true...

Testcase : http://jsfiddle.net/QJA7z/1/

**Comment by alexeymalihin** [comment]
Any updates on this? :up:

**Comment by adrienrn** [comment]
Confirm this behavior for defined test on undefined property of objects :) !

**Comment by plepe** [comment]
Confirmed. I just pushed tests for these issues, based on the commit from @jopdeklein. Unfortunately the referenced 'fix' does not work (see the second commit in the pull request #310).

**Comment by plepe** [comment]
Yep, found it, should be fixed. In fact it was just one small change, that if a property of an object can't be found, it should use the value `undefined`, but it used the value `null`.

**Comment by dave-irvine** [comment]
Believe this is resolved in #310.
