### ISSUE TITLE
Pre-compiled includes/extends

### ISSUE THREAD

**Issue by aach** [twigjs/twig.js#173]
Would be wonderful if the include/extend resolves in compilation time.
Sometimes is not necessary to load them asynchronously (if the include is mandatory and its not inside a flow control structure like an if).
Or at least to have the option to make them at compilation time :+1:

**Comment by brunowego** [comment]
+1

**Comment by signal-intrusion** [comment]
:+1:

**Comment by willrowe** [comment]
There are no plans for this at this time.
