### ISSUE TITLE
Support extended ternary operator

### ISSUE THREAD

**Issue by noisysocks** [twigjs/twig.js#179]
twig.js does not currently support the [extended ternary operator](http://twig.sensiolabs.org/doc/templates.html#other-operators).

    {# as of Twig 1.12.0 #} 
    {{ foo ?: 'no' }} is the same as {{ foo ? foo : 'no' }}
    {{ foo ? 'yes' }} is the same as {{ foo ? 'yes' : '' }}

**Comment by evgenius** [comment]
Thanks @noisysocks , I'll take a look.

**Comment by olets** [comment]
+1

Would love to see support for these shorthands. They were introduced long enough ago now that it's reasonable to experienced Twig users to rely on them (I know it trips _me_ up on a regular basis ;)

**Comment by dave-irvine** [comment]
I agree. I'll try and get this fixed.
