### ISSUE TITLE
precompile templates using browserify

### ISSUE THREAD

**Issue by dane-harnett** [twigjs/twig.js#205]
Hi all,

I have created a browserify transform to precompile twig templates....
https://github.com/dane-harnett/twigify

However I have come up against a road block when using templates that include/extend other templates.

I'm hoping someone with more knowledge of the twig internals might be able to help out with how we might be able to go about completing this.

My hope is that I can pre-compile twig templates and use browserify to bundle all the dependancies together.

**Comment by evgenius** [comment]
Hi @dane-harnett ,

You can set an ID for a template using the `id` parameter.
You should also allow using the inline templates:
```js
twig({id:'test.twig', data: '{{ "foo" }}'});
twig({allowInlineIncludes: true, data: '{% include "test.twig" %}'}).render(); // foo
```

Hopefully it answers your question.

**Comment by dane-harnett** [comment]
Hi @evgenius,

The issue is the loading of the "test.twig" template as a module using require() supplied from browserify.

I would like twig to check if there is a module by the name of "test.twig" and if so then load it automatically so that my template can include it.

**Comment by evgenius** [comment]
@dane-harnett , I am a bit confused on how your module works. Would you mind providing a working example?

**Comment by dane-harnett** [comment]
It's supposed to work like this module: https://github.com/zertosh/jstify except it compiles twig templates instead of underscore.

**Comment by dane-harnett** [comment]
@evgenius I have updated my module and added a readme, https://github.com/dane-harnett/twigify let me know if you need any more explanation :)

**Comment by signal-intrusion** [comment]
@dane-harnett Did you ever get this to work? it seems that whenever I run `template.compile` it does not include a `allowInlineIncludes: true` property on the compiled templates when I've explicitly set it in the template.

**Comment by olets** [comment]
@dane-harnett should this still be marked as a high priority twig.js issue?

**Comment by signal-intrusion** [comment]
For those stumbling into this issue for help, I remember fixing this months ago by adding `allowInlineIncludes: true` to each template at runtime (ie. client-side) just before it is rendered. I haven't revisited in a long time so I'm not sure whether it's still an issue.

**Comment by dane-harnett** [comment]
@olets No I don't think it would still be high priority.

It's worth mentioning that we ended up using webpack instead of browserify and use this package (https://www.npmjs.com/package/twig-loader) to pre-compile our twig.js templates

**Comment by olets** [comment]
Glad you got it working @dane-harnett! I'll have to check out twigify - I have a back-burner project it might be cool for. Thanks for the tip @signal-intrusion 

@evgenius sounds like we can drop this label

**Comment by dave-irvine** [comment]
I'm actually going to close this and advise people use Webpack instead.
