### ISSUE TITLE
Optional Client Side Compiler; better Performance & Speed !!

### ISSUE THREAD

**Issue by SusanthCom** [twigjs/twig.js#229]
#Suggestion

It will be nice, if we could provide two version of `twig.js` for browsers like :
1. `twigjs-core.min.js` ( no compiler, thin code )
2. `twigjs-full.min.js` ( with compiler, fat code )
This will reduce the file size and improve performance ( especially in mobile ), in situations where compiled template is always provided from server.

**dustjs** provides such facility :
 // Include `dust-core.min.js` or `dust-full.min.js` on your page. If you will be compiling templates in the browser, use `dust-full.min.js`  ( http://www.dustjs.com/guides/setup/ ) //

**Comment by evgenius** [comment]
@justjohn What do you think?
Just to try I removed all "compile" functions in twig.js and minified it. Its size reduced from 82K to 73K.
As far as I know the compiled templates have much bigger sizes than the source templates.
So I doubt there will be any benefit in terms of initial load speed.
But performance may increase dramatically which is sensitive for mobile platforms.
I'll write some tests to see how big the performance increase is in this case.

**Comment by webberig** [comment]
I made an effort too a while ago, I posted my findings in #253. The compiler itself doesn't have a lot of code. I think the tokenizer could be removed too but I didn't succeed in doing that.

**Comment by dave-irvine** [comment]
Closing this in favour of #80
