### ISSUE TITLE
Include with variable or string concatenation does not work

### ISSUE THREAD

**Issue by henrmota** [twigjs/twig.js#231]
browser
{% set template = 'template'~'.twig' %}
{% include template %}

**Comment by henrmota** [comment]
My fix

line 2602  
if(file === undefined)
                    file = context[token.stack[0].value];

**Comment by evgenius** [comment]
Hi @henrmota ,

Could you give more details?
I can't reproduce the issue.
Here's my example:
```js
twig({id:"template.twig", data:"foo"});
twig({
  allowInlineIncludes: true,
  data: '{% set template="template"~".twig" %}{% include template %}'
}).render(); // "foo"
```

**Comment by henrmota** [comment]
This happens in the browser. I have a bunch of twig files that i print in html body as a <script>...</script>.

$("script[type='twig']").each(function()
{
    var id = $(this).attr("id");
    var data = $(this).html();
    twig({allowInlineIncludes:true,id:id,data:data});
});

then:

 twig({ref:"name.twig"}).render(data);

**Comment by micahgodbolt** [comment]
hey @evgenius,  are there any updates/progress on this issue? I'd like to use twig.js for a large project, but I need to be able to use {% include myvar.template using myvar.data %}

**Comment by micahgodbolt** [comment]
hrm....tried this again. seems to work now.

**Comment by henrmota** [comment]
the problem is with data only


browser
{% set template = 'template'~'.twig' %}
{% include template with field only %}

**Comment by evgenius** [comment]
@henrmota Thanks, yesterday I experienced the same issue. It's an issue with the `only` parameter.
Hopefully I'll be able to fix it soon.

**Comment by dave-irvine** [comment]
I can't replicate this. Please reopen if you're still having an issue.

**Comment by JohnAlbin** [comment]
> Thanks, yesterday I experienced the same issue. It's an issue with the only parameter.

Oooh! Thanks for that insight, @evgenius. I'm able to work-around my issue knowing this.

I've re-opened this issue in #394
