### ISSUE TITLE
Use it with Consolidate?

### ISSUE THREAD

**Issue by slavafomin** [twigjs/twig.js#234]
Hello!

Is it possible to use this great package with Consolidate?

I think it will be a good option.

Thanks!

**Comment by evgenius** [comment]
Hi @slavafomin ,

From what I can see, twig.js is not supported by Consolidate yet.
But it's pretty straightforward to add it to Consolidate.
Let's leave this issue open so someone can handle it one day unless you'd like to do it yourself.

**Comment by madeofpeople** [comment]
This is sort of a big deal, as compatibility with express, and consolidate supporting static generators (metalsmith for example) would rely on this to function seamlessly.

**Comment by dave-irvine** [comment]
Hi, @madeofpeople @slavafomin 

I think this got added to Consolidate? https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L472

If someone wants to check it actually works, then great :) Otherwise, closing!
