### ISSUE TITLE
{% use "blocks.html" with sidebar as parent_sidebar %}

### ISSUE THREAD

**Issue by raynor85** [twigjs/twig.js#257]
Use statement seems to work, but if you want to redeclare the name of blocks in the current scope, node.js cast this error:

TwigException: Twig.expression.type.variable cannot follow a Twig.expression.type.string at template:36 near 'with...'
Error parsing twig template views/parkers/hpi-check/nmr-help.twig:
TypeError: Cannot read property 'forEach' of undefined

**Comment by dritter** [comment]
:+1: I have the same problem. :(

**Comment by plepe** [comment]
Sorry for not reacting earlier. Could you post an example which we could use as test?

**Comment by gcpantazis** [comment]
+1, ran into this today as well.

**Comment by dave-irvine** [comment]
@gcpantazis Do you perhaps have a code sample I can test against?

**Comment by olets** [comment]
Examples of `use with`, and `parent()` with `use`, and `{{block('blockname')}}` are at http://twig.sensiolabs.org/doc/tags/use.html. Here's a twigfiddle for every case http://twigfiddle.com/5mckud

**Comment by willrowe** [comment]
Fixed in #579.
