### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by thetiby** [twigjs/twig.js#265]
@justjohn Thank you for your hard work on this!

Is there a changelog that we can look at when updating to make sure to account for any breaking change or apply a better solution implemented in the updated version?

Also, a minor thing: the 0.8.4 version [still says](https://github.com/justjohn/twig.js/blob/master/twig.js#L2) 0.8.3 on line 2.

**Comment by plepe** [comment]
I created a CHANGELOG for the merge branch (see #280) which collects some of the current pull requests. Do you think this is sufficient? https://github.com/plepe/twig.js/blob/merge/CHANGELOG.md

**Comment by r3wt** [comment]
@plepe do you want to fork and continue this project? it appears that justjohn is done supporting the project and it will then die

**Comment by plepe** [comment]
I think that Twig has a lot of potential, especially with client rendering via Twig.js. It would be sad to see the project die, therefore yes - although I can't say if I can support the project for a long time. I'll need help from the community ...

**Comment by connorhu** [comment]
My plan is make the library full compatible with the php version. Especially the form part from symfony.
I started to make a better lexer in my fork:
https://github.com/connorhu/twig.js/blob/master/src/twig.lexer.js

**Comment by plepe** [comment]
@connorhu Yeah, I've already noticed your code. Looks pretty nice :-) I thought you'll create a pull request when you are ready. I guess this is something for a major release like 0.9.0, isn't it?

**Comment by r3wt** [comment]
@plepe i am down for participation since i am using this fairly extensively, but if justjohn is not to support he needs to add contributors to the repo so that it may be maintained and improved.

**Comment by plepe** [comment]
@r3wt I wrote an email this morning (MET timezone), now waiting for reply.

**Comment by justjohn** [comment]
@plepe - I added you as a contributor to the repo - as you've already discussed, I'm not very active on the project anymore, but I do want to see it move forward. I'll have to give some though to the side-effects of moving the repo to an organization.

@connorhu - Supporting functionality outside of twig php core is great - in general you should do it as an extension to twig.js, just like symfony provides extensions to twig php. It'd be nice to have a set of common twig php extensions mirrored for twig.js.

**Comment by evgenius** [comment]
@justjohn Thanks for adding a new maintainer. I'm not able to help this
project much at the moment.

**Comment by connorhu** [comment]
@justjohn The lexer is the first step. My plan is port every feature of twig.

**Comment by plepe** [comment]
@justjohn Thank's a lot! I'm quite busy with family matters myself :) Looking forward for future activity in this repository.

Btw, the lexer of @connorhu is not an extension, but a replacement of the current parser (as far as I understand).

**Comment by plepe** [comment]
An advantage that I see when using an organisation as head of twig.js, we can create repositories for extensions, e.g. for #271 .

**Comment by justjohn** [comment]
@plepe @connorhu Got it on the lexer - I've gotten used to people asking for symfony filters/etc... in twig.js and have a mostly automatic response to it :/ My only request for a replacement lexer is that it's at least as fast as the current one.

I went ahead and created the organization github.com/twigjs, According to the github docs (https://help.github.com/articles/transferring-a-repository/) it looks like transferring is a pretty seamless process, with all old links and remotes being forwarded, so I may go ahead and do that early January.

**Comment by plepe** [comment]
The CHANGELOG.md file is now on master. It includes all changes since 0.8.4. I'd like to wait a few days if there are any problems before tagging a 0.8.5 release. Maybe I should tag a 0.8.5-rc1 release candidate?
