### ISSUE TITLE
Connecting with Drupal 8

### ISSUE THREAD

**Issue by staminna** [twigjs/twig.js#272]
Hi

I have twig.js loaded in the header of a dynamically generated HTML Drupal page, but when I add the as in the example {{ backed_cup }} to the page.html.twig file, there is nothing.
This is my first try at Node.js, so please bare with me :)

Can someone help with a simple example on how to get a Node.js string through?

var http = require('http');
var express = require('express');

app = express();

app.use(function(){
  app.set('views', __dirname + '/views');
// example template location could be /dir/templates/page.html.twig

  app.set('view engine', 'twig');
  app.set('view engine', 'html.twig');
  app.engine('html', twig.__express);
});

app.get('/', function(req, res){
    res.render('index.twig', {
        message : "Hello World"
    });
});

var Twig = require('twig'), // Twig module
    twig = Twig.twig;       // Render function

var template = twig({
    data: 'Twig {{ baked_good }} is on Nodejs objects.'
});

    console.log(
        template.render({baked_good: 'some string'})
    );

app.listen(9999);

// Configure our HTTP server to respond with Hello World to all requests.
var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.end("Hello World\n");
});

server.listen(8000);
console.log("Server running at http://127.0.0.1:8000/");

console.log(template.render({baked_good: some_variable.text}));

I certainly know I am missing something, and I could use some help. Thank you.

**Comment by krisak** [comment]
Well either i am missing something or you are putting server side javascript into a browser. Node.js is server side javascript not browser, you dont need that.
If you want to render template with twig in a browser you just need 
this (you must have twig.js loaded in browser of course)

var template = twig({
    data: 'The {{ baked_good }} is a lie.'
});

console.log(
    template.render({baked_good: 'cupcake'})
);

**Comment by staminna** [comment]
Thanks for replying me. It works on the browser via normal javascript.
I need to theme Node.js strings into browser because there are some modules with functionality I need to render on Drupal 8's new twig theme engine.

**Comment by dave-irvine** [comment]
No update for 30 days, closing.
