### ISSUE TITLE
Expose filters so that they can be re-used / called from inside another?

### ISSUE THREAD

**Issue by sjuvonen** [twigjs/twig.js#307]
Currently registered filters seem to be completely private and hidden from the exported Twig object, so they cannot be accessed at all outside templates. Usually template engines expose the filters, so I don't know why Twig.js is different in this manner. 

Is there a specific reason for not exposing filters or could it be done? It seems to be about only adding one line, Twig.exports.filters = Twig.filters, somewhere in the code.

**Comment by plepe** [comment]
Sounds interesting, don't know if there's a reason to not expose it. Any thoughts by @justjohn or @evgenius about this?
