### ISSUE TITLE
More general solution for overriding custom loaders

### ISSUE THREAD

**Issue by plepe** [twigjs/twig.js#314]
Pull request #301 introduced a way to override template loaders. I think this should be a more general solution, because it also includes the call to `new Twig.Template(params);`. Pull request #309 introduces the `source` tag which uses nearly the same loader as the template loader, but does not call `new Twig.Template()`.

Maybe we should separate loading from compiling the template, then we can use the same loader for all kinds of loads. It would also be possible to extend available compilers, e.g. add markdown (the markdown extension could include a markdown file with `{% markdown "path/to/file.md" %}`.

@createvibe, @bkotos: what do you think?

**Comment by bkotos** [comment]
@plepe This sounds like a better solution.  I agree it would make modifying the loading process or adding new compilers easier.  I'd be glad to help decouple these.

**Comment by createvibe** [comment]
@plepe, so basically, don't instantiate the template from the loader, just modify params with the data and any other relevant properties?

The only problem I see with that is the asynchronous loading of the template.  I guess loadRemote can wrap the callback and instantiate the template itself, based on the modified params.  But then, the template returned from the callback and the template returned from the loadRemote function, if not async, would need to be the same reference.  It might be a little tricky, but I can see a way to do it.  Is this something like what you had in mind?

**Comment by r3wt** [comment]
we should seperate the load and the loadInline functions completely. they serve different purposes. it may violate DRY but thats ok. we're not building a front end code base, were building a library, and whats best for the implementation is not some meaningless pursuit of best practices. 

**loadInline could work like this:**

> loads a template inline and returns it asynchronously. to avoid huge perf loss (due to waiting on template from include), we insert a randomized placeholder tag and continue compiling template as normal. after compile is done and the loader has returned we compile that. to implement we need to support recursion to infinite depths, so we need to manage state. in node this is accomplished with something like async each. in raw js, this is accomplished with a two variables and a single function:

```js
var nInlineTemplates = 0;
var nInlineFinished = 0;

var inlineTemplateReady = function(){
	nInlineFinished += 1;
	if(nInlineTemplates > 0 && nInlineTemplates == nInlineFinished){
		//were done call whatever needs to be called
		finalizeDocument();
	}	
};
```


possible hairy. i'll try to throw together an example of how this can be possible as soon as i get achance.

**Comment by willrowe** [comment]
I believe this has been resolved since loaders can now be swapped out depending on the application context.
