### ISSUE TITLE
if statement with "is not null" and "in_array" check throws error

### ISSUE THREAD

**Issue by timovanderzanden** [twigjs/twig.js#316]
I have an if statement like `{% if array_var and 'value' in array_var %}...{% endif %}`, while this works in Twig PHP, it doesn't in Twig JS. I have tried it with multiple notations, including `('value' in array_var)`, etc...

It throws an error `Cannot read property 'indexOf' of null`, while I expect it to assert the first part of the if statement before searching the needle in the array.

**Comment by dave-irvine** [comment]
I think I fixed this in #344
