### ISSUE TITLE
Allow Twig.log to be overridden

### ISSUE THREAD

**Issue by tremby** [twigjs/twig.js#318]
I want to be able to send any error messages to an exception handling service. At present as far as I can see there is no way to hook in to Twig.log, which always just outputs to the console at least in node.

Any interest in adding this feature? It could either be exposing the option to override the log functions, or firing an event when errors happen, or possibly something else.

**Comment by plepe** [comment]
You are right, right now Twig.log is extremely simple (src/twig.core.js, lines 153-171). I think it would be interesting to have a way of overriding the log functions. Do you want to come up with a pull request?

**Comment by dave-irvine** [comment]
Is this the same as #335 ?

**Comment by tremby** [comment]
Near enough, I think.

**Comment by dave-irvine** [comment]
Closing this one then as #335 offered a PR and I already did some investigation over there.
