### ISSUE TITLE
Custom tag definitions with the same name

### ISSUE THREAD

**Issue by iby** [twigjs/twig.js#322]
I want to define the same tag that can be used either with an argument or block content, which also can use an argument.

``` twig
{% foo %}bar{% endfoo %}
{% foo '~/bar.file' %}
{% foo '~/bar.file' %}bar found{% endfoo %}
```

I followed the [guide](https://github.com/justjohn/twig.js/wiki/Extending-twig.js-With-Custom-Tags) to come up with the following, but it simply matches the first definition and I get error saying that either it can't compile template or the closing tag is missing.

``` js
Twig.exports.extendTag({type: "foo", regex: /^foo\s+(.+)$/, …})
Twig.exports.extendTag({type: "foo-block", regex: /^foo(?:\s+(.+))?$/, …})
```

It seems the problems occurs because the regex matches both cases, and the solution would be to allow definition to work with both `next: []` and `next: ['endfoo']`. Is something like that possible?

**Comment by willrowe** [comment]
It is not currently possible to create a custom tag without an end tag.
