### ISSUE TITLE
Respect trace / debug / rethrow, don't do console.error all the time

### ISSUE THREAD

**Issue by ianbytchek** [twigjs/twig.js#335]
Twig printing error at first opportunity is not always a desired behaviour. For example, I'm running mocha tests to ensure template rendering fails, I use `rethrow` option and handle the error myself. That made things super confusing – no errors were detected / thrown, but console was all flashing red saying the opposite.

It would be wise to disable `Twig.log.error(…)` when `{rethrow: true}`, it directly implies the error will be handled elsewhere. Another alternative is to check `debug` / `trace`, but naturally error are expected to get a different treatment. Just throwing options at the table. 

Happy to PR, let know in the comments if agree with the proposed.

**Comment by dave-irvine** [comment]
Happy to get a PR.

The code you're looking for is probably around https://github.com/twigjs/twig.js/blob/master/src/twig.core.js#L128

**Comment by dave-irvine** [comment]
Actually it looks like its already kind-of supported?

https://github.com/twigjs/twig.js/blob/master/src/twig.core.js#L721
https://github.com/twigjs/twig.js/blob/master/src/twig.core.js#L787

**Comment by ericmorand** [comment]
@dave-irvine Not, it's not supported:

`Twig.log.error("Error parsing twig template " + this.id + ": ");
            if (ex.stack) {
                Twig.log.error(ex.stack);
            } else {
                Twig.log.error(ex.toString());
            }`

As you can see, there is no way to prevent the error from being logged to the console.

**Comment by ericmorand** [comment]
Made a PR for this one:

https://github.com/twigjs/twig.js/pull/422
