### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by plepe** [twigjs/twig.js#359]
When updating to the newest version I noticed that the Makefile is gone. I found documentation in the Contributing guidelines, therefore I managed.

But:
* README.md still mentions `make`
* `npm build` didn't create any files - `npm test` did
* `twig.min.js` is gone?

**Comment by dave-irvine** [comment]
```npm build didn't create any files - npm test did```

What version of npm are you on? From memory, `npm test` is the only default script older npm understands, everything else you would have to say `npm run build`.

**Comment by plepe** [comment]
`npm run build` works. I have version 3.8.6.

**Comment by dave-irvine** [comment]
I've removed make references from the README in #360
