### ISSUE TITLE
text inside spaceless tag is escaped when Twig autoescape is on

### ISSUE THREAD

**Issue by JohnAlbin** [twigjs/twig.js#372]
I have the Twig autoescape feature turned on so it is as close to the PHP environment as possible.

When I use a spaceless tag, all of the text inside it (including HTML markup that is in the Twig template) is HTML escaped.

Example:

``` twig
{% spaceless %}
  <ul>
  <li>Hello</li>
  <li>World</li>
  </ul>
{% endspaceless %}

```

What I expect to be outputted:

``` html
<ul><li>Hello</li><li>World</li></ul>
```

What is actually output:

``` html
&lt;ul&gt;&lt;li&gt;Hello&lt;/li&gt;&lt;li&gt;World&lt;/li&gt;&lt;/ul&gt;
```

**Comment by olets** [comment]
Just to clarify: without the `{% spaceless %}` you are getting the expected
    ```<ul><li>Hello</li><li>World</li></ul>```
right?

**Comment by ryuran** [comment]
Right

```
var Twig = require('twig');

var tpl = Twig.twig({
	autoescape: true,
	data: "{% spaceless %}\n <ul>\n	<li>Hello</li>\n	<li>World</li>\n  </ul>\n{% endspaceless %}"
});

console.log(tpl.render());
```

return:
```
{ [String: '&lt;ul&gt;&lt;li&gt;Hello&lt;/li&gt;&lt;li&gt;World&lt;/li&gt;&lt;/ul&gt;'] twig_markup: true }
```

But without autoescape it returns:
```
<ul><li>Hello</li><li>World</li></ul>
```

**Comment by dave-irvine** [comment]
So what happens if you turn autoescape off?

**Comment by ryuran** [comment]
> But without autoescape it returns:
>
> ```html
> <ul><li>Hello</li><li>World</li></ul>
> ```

It means `autoescape: false` because `false` is the default value.

**Comment by dave-irvine** [comment]
So how are you expecting autoescape to behave? Isn't it supposed to "escape" the HTML?

I don't really use PHP Twig so I'm not sure what the behaviour is supposed to be.

**Comment by ryuran** [comment]
```javascript
var Twig = require('twig');

var tpl = Twig.twig({
	autoescape: true,
	data: "\n <ul>\n	<li>Hello</li>\n	<li>World</li>\n  </ul>\n"
});

console.log(tpl.render());
```
return:
```javascript
{ [String: '\n <ul>\n\t<li>Hello</li>\n\t<li>World</li>\n  </ul>\n'] twig_markup: true }
```

`{% spaceless %}` shouldn't escape html. Autoescape should only affect variable, not block like `{% spaceless %}`.

**Comment by dave-irvine** [comment]
http://twig.sensiolabs.org/doc/tags/autoescape.html says that Autoescape does affect block?

Surely the example you just posted is a bug because it hasn't escaped the HTML tags?

**Comment by ryuran** [comment]
https://twigfiddle.com/mxj2ta

**Comment by dave-irvine** [comment]
OK I understand that bit, but like I said, the docs say I should be able to wrap a block:

https://twigfiddle.com/mxj2ta/2

Why isn't *all* the HTML escaped?

Maybe I am just being stupid?

**Comment by dave-irvine** [comment]
Ahhhh, here we go:

> Twig does not escape static expressions:

```
{% set hello = "<strong>Hello</strong>" %}
{{ hello }}
{{ "<strong>world</strong>" }}
```

> Will be rendered `"<strong>Hello</strong>` **world**".

**Comment by ryuran** [comment]
This has nothing to do with the `{% autoescape %}` block.
It's about the `autoescape` option of twig.js.

**Comment by dave-irvine** [comment]
Yeah the option uses the same code as the block.

**Comment by ryuran** [comment]
😮 are you sure ?

If it's i don't understand this behavior
https://github.com/twigjs/twig.js/issues/372#issuecomment-265966773

**Comment by dave-irvine** [comment]
Hah, actually, I don't think twig.js supports the {% autoescape %} tag at all!

Man this is confusing.

What do you get if you do:

```
var Twig = require('twig');

var tpl = Twig.twig({
	autoescape: true,
	data: "<div>{{ escaped }}</div>"
});

console.log(tpl.render({
escaped: "<b>autoescaped</b>"
}));
```

**Comment by ryuran** [comment]
```javascript
{ [String: '<div>&lt;b&gt;autoescaped&lt;/b&gt;</div>'] twig_markup: true }
```

**Comment by dave-irvine** [comment]
OK, good, that's what I would expect. The world has not gone mad. Is that the output you would expect?

**Comment by ryuran** [comment]
Yes this example respect what I expect.

**Comment by dave-irvine** [comment]
Great, I think I have enough info to investigate now.

Basically autoescaping should only happen on variables, not static expressions. Wrapping a static expression in the {% spaceless %} tag seems to turn it into a variable and it then gets incorrectly autoescaped.

**Comment by dave-irvine** [comment]
Got it. PR incoming :)

**Comment by olets** [comment]
@dave-irvine 
> I don't really use PHP Twig so I'm not sure what the behaviour is supposed to be.

Wow then you're even more a hero than I thought for all your work on twig.js!

**Comment by dave-irvine** [comment]
Don't think I've actually ever written any PHP twig. LOL. Other than getting twigfiddles to work.
