### ISSUE TITLE
Bower distribution missing

### ISSUE THREAD

**Issue by SirWaddles** [twigjs/twig.js#374]
After updating from an older version to 0.9.5, through the bower package manager, there doesn't appear to be anything to load or require into JavaScript.

I'm not sure if I'm doing anything wrong, my bower json configuration is just

```
"twig.js": ">=0.5.8",
```

As far as I can tell, the bin, lib and src directories are ignored from bower.json, and this wasn't a problem when twig.js and twig.min.js were being built into the main directory, but that doesn't appear to be the case any more.

Is bower not supported any more? Or am I not configuring something correctly?

Thanks in advance.

**Comment by dave-irvine** [comment]
So I haven't been checking whether the bower distribution works. I wasn't aware people still used bower really, I thought most people had switched to using npm for everything?

Seeing as I've just had two Issues opened regarding Bower I guess people do still use it!

I'll investigate how to bundle things for Bower, but its not something I've ever done, and I really don't fancy complicating our release process much more.

**Comment by Blueblau** [comment]
I use bower along side npm, for things that also needs CSS bundled with it. So I would love if this would work as well 👍

**Comment by dave-irvine** [comment]
twig.min.js is built when you run `npm run build-browser`.

**Comment by tomfun** [comment]
Could anyone explain right way to use npm instead of bower please, sorry if this question is in wrong theme.

**Comment by dave-irvine** [comment]
Ok the fact that I have to store the compiled and minified version in git pretty much seals this for me. If this was a compiled language and I had to store my binary in git for bower to work, that would never fly.

I'll let you do your own searches for this, but I don't seem to be the only one who thinks this way: https://www.google.co.uk/search?q=use+npm+instead+of+bower

If someone wants to start another repository that takes the current twig.js npm package, runs the build job and then publishes to bower, go ahead, but this isn't something I want to maintain.

@Blueblau To get css bundles as well, have you considered Webpack?

**Comment by olets** [comment]
@SirWaddles just be clear: you aren't still just getting 0.5.8? Don't know if Bower's added extended support for semver matching, but in my understanding of npm updates to versions under 1.0.0 won't be picked up (that is, for example `^` won't work until v1.0.0)

**Comment by SirWaddles** [comment]
Yea, I checked that. It is using the latest version. I'm inclined to agree with @dave-irvine, storing the compiled version in the git repo is kind of bodgey. I'm already using npm and webpack with some projects, this was just some legacy stuff using SpBowerBundle and capifony to deploy, which made it integrate with Symfony and Composer really well.

I should be able to move to npm without too much hassle.

**Comment by IceReaper** [comment]
The build process does not work under windows. Before any discussion breaks out "who uses windows for serious development?" - cannot use anything else as the it infrastructure is enforced by the company. This included no possibility to setup a VM. Either this should work under windows too, or a browser version should be uploaded somewhere. Else this would lock out me and others who are forced to use windows from this project. (:: in a filename, directory seperators, environment variable...)

**Comment by dave-irvine** [comment]
I'll try and work on getting Travis to upload build artifacts to the Releases page on GitHub, I just don't know how yet.

**Comment by olets** [comment]
I propose we `unregister` the bower components `twigjs` and `twig.js`. I'd love to see someone take on https://github.com/twigjs/twig.js/issues/374#issuecomment-222958349 (yes @dave-irvine there are definitely still people using bower. npm isn't really suitable for front-end work yet - see [npm's write-up of the issues](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging)) but the existing registrations will just mess up anyone who thinks including them will include twig.js

**Comment by alborq** [comment]
I thinks bower install method MUST be maintain. 

Same problem, i need use twig.js for frontend dev (with backbone) but ;
- do not work on windows
- on linux, install run, but dist file and source is not here... 

How solve ?

**Comment by olets** [comment]
@alborq as an end user, there's nothing you can do to solve this right now. If we can interest someone who knows their way around Bower, we'll hopefully be able to keep the package updated.  Sorry that wasn't the answer you were hoping for.

If you can use [gulp](https://github.com/gulpjs/gulp), there's [gulp-twig](https://github.com/zimmen/gulp-twig). Note that as of this writing you'll need to use [this fork](https://github.com/olets/gulp-twig/tree/update-dependencies) to get the latest twig.js - in your package.json that's

    "gulp-twig": "olets/gulp-twig.git#update-dependencies"

**Comment by philsbury** [comment]
Anyone looking for a bower build, I've created one and will keep it inline with the main project as best I can. To installL

`bower install twigjs-bower --save`

Hope it's useful to some of you

**Comment by dave-irvine** [comment]
Thanks @philsbury!

**Comment by alborq** [comment]
Someone can add this information into documentation ? Thanks @philsbury

**Comment by dave-irvine** [comment]
@alborq I did already https://github.com/twigjs/twig.js#bower

**Comment by alborq** [comment]
@dave-irvine my bad... thanks !
