### ISSUE TITLE
Stop using the deeply flawed phpjs library

### ISSUE THREAD

**Issue by JohnAlbin** [twigjs/twig.js#375]
phpjs 1.3.2 includes this in its package.json:

```json
  "dependencies": {
    "cli": "0.4.4-2",
    "deep-equal": "0.1.2",
    "glob": "3.2.1",
    "js-beautify": "1.4.2",
    "mocha": "1.17.0",
    "send": "0.1.0",
    "underscore": "1.5.2"
  },
```

**No node.js library should ever include mocha as a dependency.** mocha is for test suites and should be added as a dev dependency.

While phpjs was released in 2014, this bug wasn't fixed until April 1 of this year in https://github.com/kvz/locutus/commit/303ffd6d84414f4605bd0e78c5f63d8913815a98 and then released as "locutus 1.3.2" even though locutus 1.3.2 !== phpjs 1.3.2. And the old "phpjs" package name has been abandoned with the broken phpjs left as phpjs 1.3.2 on npmjs.

Here's what npmjs says about the new locutus module:

![screen shot 2016-05-28 at 13 50 16](https://cloud.githubusercontent.com/assets/33429/15625504/46976f20-24db-11e6-9aee-559df35e5b96.png)

I have some concerns about the locutus project being properly maintained.

**Comment by dave-irvine** [comment]
Looks like phpjs 1.3.2 has been left as a backwards compatible release, new development is in locutis. Will look at moving over soon.

**Comment by JohnAlbin** [comment]
> Will look at moving over soon.

Okey-doke. I created a PR for you. #376
