### ISSUE TITLE
Mongoose.find() not working with res.render

### ISSUE THREAD

**Issue by TheMaxoor** [twigjs/twig.js#377]
In a NodeJS application using Express 4, I retrieve Tickets with mongoose and I need to render them. 

Here is the first thing I tried : 
```javascript
app.get('/' , function(req, res){
  var tickets = null;

  Ticket.find({}, function(err, fetchedTickets) {
    if (err) throw err;
    
    tickets = fetchedTickets;
    // console.log(tickets) shows my Tickets in my CLI when found
  });

  res.render('front/home', {
    'tickets': tickets // tickets is null 
  });
});
```

During my hours of search I saw that .find() method was async and res.render() wasn't. 
So I tried this : 

```javascript
app.get('/' , function(req, res){

  Ticket.find({}, function(err, fetchedTickets) {
    if (err) throw err;
   
    res.render('front/home', {
        'tickets': fetchedTickets
    });
  });
});
```

This code freezes my page and outputs this in my CLI : 
```
<--- Last few GCs --->

   23216 ms: Scavenge 1398.7 (1458.1) -> 1398.7 (1458.1) MB, 3.0 / 0 ms (+ 13.6 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   24098 ms: Mark-sweep 1398.7 (1458.1) -> 1398.7 (1458.1) MB, 881.4 / 0 ms (+ 29.2 ms in 6 steps since start of marking, biggest step 13.6 ms) [last resort gc].
   24939 ms: Mark-sweep 1398.7 (1458.1) -> 1398.7 (1458.1) MB, 841.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x485e75e3ac1 <JS Object>
    2: /* anonymous */(aka /* anonymous */) [/path/to/my/project/node_modules/twig/twig.js:~3825] [pc=0x23fc1625b1f9] (this=0x485e7504189 <undefined>,times=4907)
    3: /* anonymous */(aka /* anonymous */) [/path/to/my/project/node_modules/twig/twig.js:3854] [pc=0x23fc162b0fd9] (this=0x485e7504189 <undefined>,variable=0x3d0e6708b7d1 <a NativeConnection with map 0x2e2fe4a439d1>)
 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

Is there a way to handle this properly ?
(I'm kinda new in the NodeJS world, please forgive me if the answer is obvious to you)

PS: I'm on Mac OS X El Capitan

**Comment by dave-irvine** [comment]
Well I'm guessing that `fetchedTickets` is large? How many items in this collection?

**Comment by TheMaxoor** [comment]
It's not large at all, it contains only 3 tiny items.

**Comment by dave-irvine** [comment]
What happens if you try to render your template without Express? So:

```
var Twig = require('twig'), // Twig module
    twig = Twig.twig;       // Render function

var template = twig({
path: 'front/home'
});

template.render({
'tickets': []
});
```

**Comment by TheMaxoor** [comment]
With this code I had to update the path to something like `dirname__ + /blah/blah/front/home.twig` in order to find the template. 
After finding it I've got this error : 
```
TypeError: template.render is not a function
```
That's strange, I didn't forget to include the Twig module and the render function as you told me.

**Comment by dave-irvine** [comment]
Possibly your template is not compiling? If you `console.log(template)` before the render call, do you get anything?

**Comment by TheMaxoor** [comment]
I get `true` with `console.log(template)`

**Comment by dave-irvine** [comment]
OK, that is wrong, so lets try a simpler example to make sure twig is working at all:

```
var template = twig({
    data: 'The {{ baked_good }} is a lie.'
});

console.log(
    template.render({baked_good: 'cupcake'})
);
```

**Comment by TheMaxoor** [comment]
It works, it outputs `The cupcake is a lie` (nice reference by the way)

**Comment by dave-irvine** [comment]
OK so this indicates there might be a problem with your template? How complex is the .twig file you are using, does it extend other templates, etc?

With:

```
var template = twig({
path: __dirname + '/blah/blah/front/home.twig'
});
```
You can also pass in:

```
var template = twig({
path: __dirname + '/blah/blah/front/home.twig',
debug: true,
trace: true
});
```

and hopefully you will get more useful output.

**Comment by TheMaxoor** [comment]
Wow ! It outputs a lot of informations but nothing looks like an error.

[Here is the content with debug enabled](http://pastebin.com/4EiPJQS4) (sorry for this huge paste)

My home.twig file extends a layout with `{% extends '../layout.twig' %}` and the layout himself extends a base file like so `{% extends 'base.twig' %}`

My file structure looks like this for my views : 
```
views /
   |
   base.twig
   layout.twig
   front /
      |
      home.twig
```

Note that the template used to work in "front only" mode, when I didn't try to handle my database data.

Thanks for the help by the way. 😄

**Comment by dave-irvine** [comment]
I really can't think of a situation where no errors are printed but `template` resolves to `true`. It should be an object with functions attached to it, one of which is `render`. We know this because the simple example works.

**Comment by TheMaxoor** [comment]
FINALLY RESOLVED !! 
I had twig comments in my home.twig `{# Like That #}`, I removed them, and it works fine now !

I used this code to render my template : 
```javascript
Ticket.
   find({}).
   exec( function ( err, tickets ){
     if( err ) return next( err );
     res.render( 'front/home', {
         'tickets' : tickets
     });
   });
```

**Comment by dave-irvine** [comment]
Congratulations on debugging your issue! Let's close this Issue and raise a new one for comments not working.

**Comment by ishu3101** [comment]
I'm also getting the **TypeError: template.render is not a function** error message. This is what my code looks like.

**index.js**

```
var fs = require("fs");
var path = require('path');
var twig = require("twig").twig;

var tpl = (__dirname + "/index.twig");
var template = twig({
	path: tpl
});

return template.render();
```

**index.twig**

```
<p>Hello world in Twig</p>
```

Everytime I run the program, I get the **TypeError: template.render is not a function** error message, but then when I refresh the page. I get the output **Hello world in Twig**
