### ISSUE TITLE
extending twig while using it with consolidate

### ISSUE THREAD

**Issue by maqboolkhan** [twigjs/twig.js#388]
i am successfully using it with `consolidate` but now i cant figure out how to extends `twig` while using it with `consolidate`

**Comment by olets** [comment]
Hi! Is this a question about [extending twig](http://twig.sensiolabs.org/doc/advanced.html)? Are you talking about [consolidate.js](https://github.com/tj/consolidate.js/) or some other "consolidate"? What's the problem you're running into?

**Comment by maqboolkhan** [comment]
im talking about this 

[https://github.com/twigjs/twig.js/wiki/Extending-twig.js](https://github.com/twigjs/twig.js/wiki/Extending-twig.js)

but now i cant figure out if i use `twig` with  `[consolidate.js](https://github.com/tj/consolidate.js/)` then now how i can extend `twig.js` ?

**Comment by olets** [comment]
Cool. The first thing to figure out is whether the problem is twig, twig.js, or consolidate.

Does your extend work in (php) Twig?

If yes, does your extend work in twig.js when you don't use consolidate?

**Comment by maqboolkhan** [comment]
this is not any kind of problem im just confuse that if i use `twig.js` by using `consolidate` then how will able to extend twig??

**Comment by dotmagic** [comment]
@maqboolkhan There's a example on consolidate.js site, just scroll down to "Template Engine Instances". The example is for nunjucks but it basically the same for others.

**Comment by maqboolkhan** [comment]
i did 

`cons.requires.twig = twig.configure();`

it throws 

```
TypeError: twig.configure is not a function
    at Object.<anonymous> (C:\Users\maqi\Desktop\component\conso-test\index.js:4:27)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

```

:( @dotmagic

**Comment by dotmagic** [comment]
@maqboolkhan Of course that won't work, twig.js has no configure()

With "its basically the same" i mean the way you can access the template engine object. 

Maybe it helps if you take a look on the source?
https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L472
