### ISSUE TITLE
Handling unsupported tags / functions

### ISSUE THREAD

**Issue by mauricoder** [twigjs/twig.js#389]
Hello

I started ussing TwigJS to use same templates files in Frontend as in Backend. I guess just as everybody.

However, when a template uses a function, tag, etc that is unsupported by TwigJS it crashes with an exception when parsing the template. It's happening often specially when extending server side Tiwg with bundles.

I've been extending twigJS with custom filters, and functions when required, and made a JS implementation when possible on JS side of server side function,s etc. Is there a better way to do this? Sometimes I'll just like to somehow just ignore tags, filters or functions not implemented by TwigJS.

Should this be fixed on TwigJS side, or can I implement another practice to fix this? Or just keep extending TwigJS with implementations or even Stubs for not supported tags, functions, and filters?

Thanks

**Comment by olets** [comment]
Don't know what sort of extending you're doing. Is #64 helpful at all?

**Comment by mauricoder** [comment]
@olets Thanks for the help. 

By extending I mean as it's documented in Twig JS wiki here:

https://github.com/twigjs/twig.js/wiki/Extending-twig.js

To implement custom functions, filters, tags. 

However, seems like it's not going to make sense.  I wanted TwigJS to stop crashing when a function, filter, etc is not available but it doesn't looks like a good idea.
