### ISSUE TITLE
Include with variable does not work when using "only" keyword

### ISSUE THREAD

**Issue by JohnAlbin** [twigjs/twig.js#394]
Re-opening #231

If you use a variable for the name of the template to include, the variable will appear to be empty if the include has an `only` keyword.

For example, this does not work:

```twig
{# example.twig #}
{% set template = "example2.twig" %}
{% include template with {items: item.below} only %}
```

It reports:
> Error parsing twig template /path/to/example/example.twig: 
> TwigException: Unable to find template file /path/to/example/

But, interestingly, if you include the variable inside the `with {}` clause, it does work:
```twig
{% set template = "example.twig" %}
{% include template with {items: item.below, template: template} only %}
```

So there appears to be some scoping error going on here.

**Comment by willrowe** [comment]
I noticed this bug a couple of weeks ago and put together a fix for it. I'll submit a pull request right now and reference this issue.
