### ISSUE TITLE
template cacheing

### ISSUE THREAD

**Issue by r3wt** [twigjs/twig.js#398]
Is it possible to autoreload templates on changes? A number of people i've came in contact with have the same gripe about twig. we need the ability to autoreload templates on changes. i'd like to take a crack at this. any comments?

**Comment by dave-irvine** [comment]
I'd welcome a PR for it. Should be possible with a file watcher and then storing the result in `Twig.templates.registry`

```
Twig.Templates.registry[template.id] = template;
```

**Comment by toptalo** [comment]
Hello, how can I reset cache for template?
