### ISSUE TITLE
Cannot install through bower

### ISSUE THREAD

**Issue by OndrejPiza** [twigjs/twig.js#402]
Hi,

I have a problem with installing your repo with bower.

It returns 

" Failed to execute 'git clone https://github.com/justjohn/twig.js.git -b v0.9.5 --progress . --depth 1' exit code of #128 

It fails during checkout, because of detached HEAD. 

Is there anything I should change?

In by bower.json it is set this way    "twig.js": "^0.8.9",

**Comment by mikeerickson** [comment]
IMHO, Bower install should be replaced by using npm install anyway.   Bower is "old school" :-)

**Comment by olets** [comment]
@OndrejPiza we're discussing Bower (and @mikeerickson the question of what parts of the development world do and don't still use it;) in #374

**Comment by mikeerickson** [comment]
@olets it was a tongue and cheek comment.  I still have projects that use bower (but all new projects only use npm)

**Comment by OndrejPiza** [comment]
Thank you for pointing me to that thread. 

If I understand correctly, bower is not or at least won't be in nearest future supported anymore. So we should migrate to npm instead.

**Comment by mikeerickson** [comment]
@OndrejPiza while not an "official" statement, trends state otherwise.

**Comment by olets** [comment]
@mikeerickson yes understood :)

@OndrejPiza that's right, twig.js doesn't currently support Bower

**Comment by OndrejPiza** [comment]
OK, I tried it experimentaly on other PC and even pure Git (TortoiseGit in my case) cannot clone this repository. 
But other guys, who are working on Linux don't have this type of problem, only I work on Windows. So it look like this has something to do with Windows.

error: unable to create file test/templates/namespaces_::.twig (Invalid argument)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by dave-irvine** [comment]
Hi @OndrejPiza. As you have said this looks like a Windows specific issue. I'll open a seperate Issue for this as its unrelated to bower.
