### ISSUE TITLE
Extends does not work with express array for views.

### ISSUE THREAD

**Issue by joscarras** [twigjs/twig.js#403]
Hello guys,

If you configure express like this:

`app.set( 'twig', twig );`
`app.set( 'twig options', config( 'twig' ) );`
`app.set( 'views', [ '/path/first/', '/some/other/path'] );`
`app.set( 'view engine', 'twig' );`

And then try to use
`{% extends 'layout/base.twig' %}`

It produces the following error:

Error parsing twig template 'path/first/some.twig: 
Error: ENOENT: no such file or directory, stat '/pathfirst,/some/other/path/layout/admin.twig'

As you can see it takes the array and adds a string to it producing the invalid path because the array toString simply does array.join(',').

This happens in the function Twig.path.relativePath.

I could try to fix this by doing a recursive check, however I don't think that the relativePath function is the place to do the check but instead higher up the function chain.

Now this was my time checking the source, so if you give me some pointer to where the check is most appropriate I can try to fix this when I get some free time.

Here is the order of functions calls and the name of the functions:
1. Block logic tokens. Format: {% extends "template.twig" %} - the parse function
2. template = this.importFile(file)
3. Twig.Template.prototype.importFile function
4. url = Twig.path.parsePath(this, file);
5. Twig.path.parsePath function
6. return Twig.path.relativePath(template, file);
7. Twig.path.relativePath function

Best regards!

**Comment by willrowe** [comment]
Template paths must be a single path, not an array.
