### ISSUE TITLE
Twig options

### ISSUE THREAD

**Issue by nkavian** [twigjs/twig.js#404]
I see in the Wiki page an example that uses "twig options", but I can't find in any of the documentation a list of all twig options.  Does a page like this exist with these details?  For example how do you disable/enable template caching?

**Comment by johny-gog** [comment]
I found [this](https://github.com/twigjs/twig.js/blob/master/src/twig.core.js#L1096) useful. There's for example `base` parameter that can set a base path for all paths without using namespaces (as in PHP `Twig_Loader_Filesystem`, but only single one)

Seems that is not well documented yet.
