### ISSUE TITLE
Improve documentation for non Express implementations

### ISSUE THREAD

**Issue by mattlo** [twigjs/twig.js#409]
It would have been helpful to know that `Twig.renderFile` can render a twig file from a given filepath. Not everyone uses Express.

**Comment by r3wt** [comment]
@mattlo following works too:

```js
var Twig = require('twig');
Twig.twig({
	path: './path/to/someFile.twig',
	method: 'fs',
	load: function(t){
		var html = ''+t.render({ foo: 'bar',url:'http://example.com'}); //render and convert to String
        }
});
```

**Comment by mattlo** [comment]
@r3wt `renderFile` abstracts the loader for you and method type for you. Your above example equates to the following:

```js
Twig.renderFile('./path/to/someFile.twig', {foo:'bar',url:'http://example.com'}, (err, html) => {
  html; //render and convert to String
})
```

**Comment by r3wt** [comment]
Right, but it too is not documented. A thread about improving documentation for a single file solves nothing, this project is poorly documented all the way around. on the flipside of that, i believe anyone who wants may freely edit the wiki.

**Comment by dave-irvine** [comment]
@mattlo Looking forward to your wiki edit or pull request :)
