### ISSUE TITLE
incorrect docs: twig is not defined in browser

### ISSUE THREAD

**Issue by peetersdiet** [twigjs/twig.js#421]
When loading the library with npm and including it in the browser, the example code errored with 'ReferenceError: twig is not defined'. I adjusted the call to the global twig-function to use Twig.twig and that fixed it. I suspect the documentation needs a minor update?

Does not work:

``` js
    var template = twig();
```

Does work:

``` js
    var template = Twig.twig();
```

twig.js version: 0.8.9
browser: FF49.0.1 on Windows 7

**Comment by santanamic** [comment]
This is the solution. Thank you.

**Comment by willrowe** [comment]
The [documentation](https://github.com/twigjs/twig.js/wiki#browser-usage) is currently correct.
