### ISSUE TITLE
Twig.min.js - Version?

### ISSUE THREAD

**Issue by cwbeck** [twigjs/twig.js#425]
I've checked out to version v0.10.0: ```twig.js-0.10.0 user$```

Run the following...

Fork and clone the twig.js git repository
Run npm install to install the development dependencies
Make your changes to the source files in src/
Add/update tests in test/
Run npm test to make sure your tests pass.
Run npm build to build the source.

Produced the twig.min.js, but showing 0.8.9:

```
/**
	 * Twig.js 0.8.9
	 *
	 * @copyright 2011-2016 John Roepke and the Twig.js Contributors
	 * @license   Available under the BSD 2-Clause License
	 * @link      https://github.com/twigjs/twig.js
	 */
```

Is this correct?

**Comment by dave-irvine** [comment]
Fixed in https://github.com/twigjs/twig.js/commit/b7abdb6de302cdad3ec1941622a0a151f9ed6cb4
