### ISSUE TITLE
Version numbers out of sync

### ISSUE THREAD

**Issue by philsbury** [twigjs/twig.js#428]
It seems the version numbers are not synced at present - the release version is 0.10.0, but compiled code (via npm install and npm run build) produce 0.8.9.

**Comment by dave-irvine** [comment]
Fixed in https://github.com/twigjs/twig.js/commit/b7abdb6de302cdad3ec1941622a0a151f9ed6cb4

**Comment by philsbury** [comment]
@dave-irvine this is back in 0.10.3, run build gives a file with version 0.10.2. Happy to create a new issue if required.

Thanks
Phil

**Comment by dave-irvine** [comment]
I think I might just remove the version number from the code. It's tricky to remember to bump it when I do a `npm version`.

**Comment by dave-irvine** [comment]
@philsbury Do you use it for anything? Or do you just notice when its out of sync? :D

**Comment by philsbury** [comment]
@dave-irvine I'm not using it as such, I'm currently looking at creating a repo with a compiled version for bower and it's just a nicety to know I'm using the right version ;)

If it's not something that can be automated at build from the package then it could be removed - can't speak for anyone else though.
