### ISSUE TITLE
Valid code

### ISSUE THREAD

**Issue by modelair** [twigjs/twig.js#437]
{% if(profile.id == account.id) %} is not valid twig, but {% if (profile.id == account.id) %} - valid! WTF?

twig.js is very buggly, like an alpha

**Comment by r3wt** [comment]
Probably just a parsing error.

**Comment by dave-irvine** [comment]
No I'm not kidding you. I think there is already an issue open for this but I can't find it right now, but you are correct, the parser has difficulty with `if(` vs `if (`.

**Comment by Cheazer** [comment]
ok, thxu. sorry for butthurt, this bug eats my time :)

**Comment by r3wt** [comment]
@dave-irvine IIRC i opened a similar thread once upon a time.

**Comment by olets** [comment]
Agree that since Twig supports `if(x)` twig.js should too. But it's a good habit to use `if (x)` anyway (or, in this case, `if x` — no need for those parentheses) to visually distinguish between statements and functions.

**Comment by toptalo** [comment]
Do we need to fix this? If yes -> I can

**Comment by dave-irvine** [comment]
@toptalo Yes please!

**Comment by toptalo** [comment]
Ok. Also will fix `elseif()` for same syntax

**Comment by dave-irvine** [comment]
Fixed in https://github.com/twigjs/twig.js/pull/570
