### ISSUE TITLE
BC since 0.9.x - Object methods lose context when called

### ISSUE THREAD

**Issue by webberig** [twigjs/twig.js#440]
I pass an object to the render function that has a getter method for this template:
```
The {{ model.getBakedGood() }} is a lie.
```
The given model has a method `getBakedGood` that returns `this.baked_good` from the `model` object.

This worked fine with twig.js 0.8.9, I've put a working demo in fiddle:
https://jsfiddle.net/mathieumaes/f9px5c63/

I can't seem to get Twig.js 0.9.x and up to work in fiddle, but if you try the given use case in a project, The getter method will return undefined because the context in which the method is called is actually the "root" context of the twig template (aka. `{ model: Object }`, and not the given `model` object.

**Comment by dave-irvine** [comment]
I probably broke it right around here: https://github.com/twigjs/twig.js/commit/af38035eef3690af8c1397f6557e7fe74f470237

**Comment by dave-irvine** [comment]
I like your loader, I'll reference it in our readme :)

**Comment by webberig** [comment]
Thanks for looking into this! I've been looking into it myself but I haven't been able to put my finger on it...

Feel free to reference to the twig-loader, it is also mentioned in the webpack docs (http://webpack.github.io/docs/list-of-loaders.html#templating)

**Comment by ericmorandcross** [comment]
I made a PR for this issue: https://github.com/twigjs/twig.js/pull/455

**Comment by dave-irvine** [comment]
Released in v1.10.3
