### ISSUE TITLE
CompileOption render error with typescript

### ISSUE THREAD

**Issue by adadgio** [twigjs/twig.js#446]
The following does not work.

```
import Twig from 'twig';
Twig.renderFile('./path/to/someFile.twig', {foo:'bar'}, (err, html) => {
  html; // compiled string
});
```

With the error:

`Argument of type "foo": String is not assignable to parameter of type CompileOptions`

**Comment by dave-irvine** [comment]
I'm guessing this is due to a problem with the typings wherever you have fetched them from.

We don't directly support typescript, so you'll need to figure out where the typings are and submit a PR there to fix them.

I'm guessing https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/twig

**Comment by adadgio** [comment]
Thanks. I'll look into that.
