### ISSUE TITLE
Bump to ≥v1 to support semver ranges

### ISSUE THREAD

**Issue by olets** [twigjs/twig.js#450]
I propose we bump the current `v0.10.3` to `v1.10.3` or maybe `v1.0.3`

npm doesn't support semver version ranges for versions less than `v1`, so there's no way to automatically use the latest version of twig.js. (E.g. `"twig": "^0.10.3"` is equivalent to `"twig": "0.10.3"` because the major level is `0`)

This is inconvenient in personal projects, and even less convenient when using a community project (for example gulp-twig often has an open pr [or two](https://github.com/zimmen/gulp-twig/pulls) looking to manually update the twig.js dependency).

Given the npm limitation, I think it's fair to think of the `1.x` range the way we're currently thinking of `0.x`

**Comment by dave-irvine** [comment]
Done
