### ISSUE TITLE
Building twig.js for browser use

### ISSUE THREAD

**Issue by akuehnis** [twigjs/twig.js#451]
I would like to use twig.js in the browser - without npm.

Where can I get the latest twig.js for browser use. I read "Run make (or make -B to force building) build them", however, I still don't know what to do :-)

Can anybody point me in the right direction? 

Thanks!

**Comment by philsbury** [comment]
The latest release version is available via bower here: https://github.com/philsbury/twigjs-bower

You can alway just download the repo if you don't use bower

**Comment by akuehnis** [comment]
Many Thanks, philsbury, that did the trick: use "Twig.twig" instead of just "twig".
