### ISSUE TITLE
Help .twig compile .html

### ISSUE THREAD

**Issue by jefffortune** [twigjs/twig.js#452]
I use webpack 2 and Express and I just started using Twig in a new project. I am having trouble finding or understanding how to compile my .twig files to .html files. It more beneficial to me to have them in .html then .js.

**Comment by r3wt** [comment]
Lol. "i use webpack but cant be bothered to write a string to an html file". Seriously, a few loc will solve your problem

**Comment by jefffortune** [comment]
I get that, I just wanted to see if there was something I was missing before doing it. I like to stick to a certain way of doing things before I deliver my own solution.

**Comment by r3wt** [comment]
@jefffortune generating static html files is beyond the scope of any templating library, but it should be doable fairly easy with `Twig.render`/ i've done it before, i can probably dig up an example if you like.

**Comment by jefffortune** [comment]
It ok, I think I am going to make a module for webpack that will handle this. I know gulp-twig did this task and wanted to make sure I wasn't duplicating something that was already implemented. Thank you for your feedback.

**Comment by francesco2you** [comment]
You can use [gulp-twig](https://github.com/zimmen/gulp-twig)
