### ISSUE TITLE
include only compile error

### ISSUE THREAD

**Issue by cjg125** [twigjs/twig.js#453]
{% include "header.html"&nbsp;only %} compile error
{% include "header.html"&nbsp;&nbsp;only %} successful～

**Comment by ianbytchek** [comment]
Seems like related to #394, using `with {}` solves this… @willrowe you made the #395 pr, any chance you can look into this one too?

**Comment by ianbytchek** [comment]
@cjg125 I don't think this should be closed, it should work fine with `{% include "header.html" only %}`, but currently requires either a space or `with {}`.

**Comment by willrowe** [comment]
#394 and #395 were related to the the template path containing a variable.
The code that @cjg125 posted [works fine in Twig PHP](https://twigfiddle.com/yecqp2). According to the [Twig documentation](https://twig.sensiolabs.org/doc/2.x/tags/include.html) it should function as a shorthand for `with {} only`.
If it does not work, then it would seem that Twig.js is not compatible with Twig PHP on this.

**Comment by i22tha** [comment]
@cjg125 Why was this closed? Needing to add two space characters is undocumented and unintuitive behavior.

**Comment by cjg125** [comment]
@i22tha   

{% include "header.html" only with {} %}

Solved my problem ～
