### ISSUE TITLE
{{ loop.length }} doesn't work with for conditionals.

### ISSUE THREAD

**Issue by jnowland** [twigjs/twig.js#458]
The `{{ loop.length }}` does not output when conditional is used on the `for` loop.

To replicate:
```
{% for i in 0..10 if true %}
  <pre>
    i: {{ i }}
    l: {{ loop.length }}
  </pre>
{% endfor %}
```
```
{% for section in sections if true %}
  {{ loop.length }}
{% endfor %}
```

see: http://twig.sensiolabs.org/doc/2.x/tags/for.html#the-loop-variable

**Comment by olets** [comment]
This should trigger a Twig error

```
The "loop.length" variable is not defined when looping with a condition.
```

From your linked doc :)

> The loop.length, loop.revindex, loop.revindex0, and loop.last variables are only available for PHP arrays, or objects that implement the Countable interface. They are also not available when looping with a condition.

**Comment by jnowland** [comment]
I believe it was silently erroring. I'll be closing this issue though!
