### ISSUE TITLE
cordova app prodblem android4.4 chrome 30 WebView

### ISSUE THREAD

**Issue by stripcode** [twigjs/twig.js#461]
#####webpack2
var path = require('path');

module.exports = {
  entry: './static/app.js',
  output: {
    filename: 'app.js',
    path: path.resolve(__dirname, 'www/js')
  },
  devtool: "source-map",

  module: {
    rules: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: "babel-loader",
      query: {
        presets: ["env"],
      }
    }]
  },

  resolve: {
    modules: [path.resolve(__dirname, "static"), "node_modules"]
  }
};

##### app.js

import Twig from "twig"

Renderer.render = function(templateUrl, data){
  var template = Twig.twig({
    href: templateUrl,
    async: false
  });
  return template.render(data);
};

on android4.4 WebView error in console
Uncaught SyntaxError: Use of const in strict mode. 

	    Twig.Promise.all = function(promises) {
	        const results = [];

	        return Twig.async.forEach(promises, function(p, index) {
	            if (!Twig.isPromise(p)) {
	                results[index] = p;
	                return;
	            }

	            return p.then(function(v) {
	                results[index] = v;
	            });
	        })
	        .then(function() {
	            return results;
	        });
	    };

I change const to var and have success.
Why module with const and not transpile

**Comment by dave-irvine** [comment]
Fixed in #470
