### ISSUE TITLE
Express multiple views dir & include

### ISSUE THREAD

**Issue by chemaxa** [twigjs/twig.js#466]
I try use multiple views directories with TwigJS & Express 
    "express": "^4.15.2",
    "twig": "^1.10.4"
Settings for express

```
app.set('views', ['src/views','src/components']);
app.set('view engine', 'twig');

```

I placed my index.twig in src/views/index.twig
And in this file i use 

`{% include 'component' with {"foo":"bar"} %}`

I placed my component in src/components/component.twig
and i got error 

```
Error parsing twig template D:\tmp\express\src\views\index.twig:
TwigException: Unable to find template file src/views,src/components\component 
```

For additional information see my repo https://github.com/chemaxa/twig-issue

**Comment by EllenFawkes** [comment]
I have the same problem. It's fixed? Or workaround exists?

**Comment by stevecohenfr** [comment]
Same here...

**Comment by willrowe** [comment]
Twig.js does not currently support this feature, but it has been requested in #225.
