### ISSUE TITLE
{% include [] %}

### ISSUE THREAD

**Issue by hatto** [twigjs/twig.js#468]
Could we have a possibility to use include with an array of templates as it is the case for the php twig?

[http://twig.sensiolabs.org/doc/2.x/tags/include.html](http://twig.sensiolabs.org/doc/2.x/tags/include.html)

**Comment by duepi** [comment]
It will be very useful too me too

Any plans on this ?

**Comment by fakemau5** [comment]
+1

**Comment by BrianWalters** [comment]
+1
