### ISSUE TITLE
Trying to create {% ifpage 'index' %} tag

### ISSUE THREAD

**Issue by webrgp** [twigjs/twig.js#469]
First of, thanks! This is a great package!

I use `gulp-twig` on my built process with browsersync and i've been trying to create a way so twig will know to display a conditional if parameter matches the outputted html file.

I proceeded to use the `Twig.exports.extendTag` to create a `ifpage` tag, and I got working hardcoding the `index` in it. Now I need help figuring out how I can get the template in question to match it. Here is my current extension:

```js
Twig.exports.extendTag({
  type: "ifpage",
  regex: /^ifpage\s+(.+)$/,
  next: ["endifpage"],
  open: true,
  compile: function (token) {
    var expression = token.match[1];

    // turn the string expression into tokens.
    token.stack = Twig.expression.compile.apply(this, [{
      type:  Twig.expression.type.expression,
      value: expression
    }]).stack;

    delete token.match; // cleanup
    return token;
  },
  parse: function (token, context, chain) {
    var page = Twig.expression.parse.apply(this, [token.stack, context]),
    output = "";

    // check if argument matches output filename/path
    if ( page == 'index') {  // <--- NEED HELP HERE
      output = Twig.parse.apply(this, [token.output, context]);
    }

    return {
      chain: chain,
      output: output
    };
  }
});

Twig.exports.extendTag({
  type: "endifpage",
  regex: /^endifpage/,
  next: [ ],
  open: false
});
```

My test case is this:

`./_layout.twig`
```twig
{% include 'partials/_header.twig' %}
{% block page %}{% endblock %}
```
`./_header.twig`
```twig
<ul class="nav nav-pills pull-right">
  <li role="presentation" {% ifpage 'index' %}class="active"{% endifpage %}><a href="index.html">Home</a></li>
  <li role="presentation" {% ifpage 'about' %}class="active"{% endifpage %}><a href="about.html">About</a></li>
</ul>
```
`./index.twig`
```twig
{% extends "_layout.twig" %}
{% block page %}
<h3>Index Page</h3>
{% endblock %}
```
`./about.twig`
```twig
{% extends "_layout.twig" %}
{% block page %}
<h3>About Page</h3>
{% endblock %}
```

So my rendered files should look like this:

`./index.html`
```html
<ul class="nav nav-pills pull-right">
  <li role="presentation" class="active"><a href="index.html">Home</a></li>
  <li role="presentation"><a href="about.html">About</a></li>
</ul>
<h3>Index Page</h3>
```
`./about.html`
```html
<ul class="nav nav-pills pull-right">
  <li role="presentation"><a href="index.html">Home</a></li>
  <li role="presentation" class="active"><a href="about.html">About</a></li>
</ul>
<h3>About Page</h3>
```

Thanks in advance!

**Comment by olets** [comment]
Sounds like this is a question about how to extend [`Twig`](https://github.com/twigphp/Twig), unless `twig.js` is giving you trouble that Twig isn't.

Keep in mind that as of this writing `gulp-twig` isn't on the latest `twig.js` - see https://github.com/zimmen/gulp-twig/pull/32

If your use case is as straight forward as the example you gave, you could do this with a variable. (In this case, you might get good help by asking at [StackOverflow#twig](http://stackoverflow.com/questions/tagged/twig))

```twig

header:
<ul class="nav nav-pills pull-right">
  <li role="presentation"{% if page == 'index' %} class="active"{% endif %}><a href="index.html">Home</a></li>
  <li role="presentation"{% if page == 'about' %} class="active"{% endif %}><a href="about.html">About</a></li>
</ul>

home:
{% extends 'layout.twig' %}
{% set page = 'index' %}

about:
{% extends 'layout.twig' %}
{% set page = 'about' %}
```

(working fiddle: https://twigfiddle.com/l8318w)

You could even do something like

```twig
header:
<ul class="nav nav-pills pull-right">
    {% for title,link in {'home':'index','about':''} %}
        <li role="presentation"{% if page == title %} class="active"{% endif %}><a href="{{ link|length ? link : title }}.html">{{ title|capitalize }}</a></li>
    {% endfor %}
</ul>
```

(working fiddle: https://twigfiddle.com/3n4zgu)

**Comment by webrgp** [comment]
Your work around is exactly what I was doing (setting a page variable) before I decide to take a shot at extending Twig. But things start to get complicated when you have "nested" routes like `/about/team`. If I can extend Twig so it can pass its file name as a variable to itself, then later I can also parse its path, relative to the root.

**Comment by willrowe** [comment]
I don't think this is possible in TwigPHP, so it wouldn't be possible here either.

If you are able to get it to work in TwigPHP, please reopen and provide an example of how.
