### ISSUE TITLE
Async template loading killed the performance...

### ISSUE THREAD

**Issue by DrParanoia** [twigjs/twig.js#472]
Hey there! Thanks for adding async template loading in include tags.

The thing is, this feature killed the performance. (751a8ba41b4275ee480d9c6de87d221e052a4b17)
My templates (that are precompiled and don't use the async loading) that took ~150ms to render now takes ~500ms. That's almost 3x times the difference.

I guess it's because the render loop is not optimised now (because of the promises).

I found out that it is much better to precompile the templates and just include them like simple JS scripts.

In ideal world the async loops should be used only if there is something to include and if the included template is not already cached. Any thoughts?

**Comment by DrParanoia** [comment]
Is anyone here? :/

**Comment by willrowe** [comment]
I would like to see some benchmarking setup for this so different changes can be compared.
Any ideas for tools that can be used for that?

**Comment by DrParanoia** [comment]
Unfortunately I don't know of any tools like that, but you can just have two tabs open with different twig.js files imported. Or you're looking for a template example that is known to work slow with the new version?

**Comment by JorgenEvens** [comment]
Hi @DrParanoia,

We have also experienced some slow rendering templates, so let me check what is going on exactly.

Only using the async loops when there is async functionality included would be the ideal situation, but we can't reliably detect this in advance without break the existing API.

The promises used by this implementation don't follow the spec in that they don't call the next function on the next tick. So while it would add some overhead, it should not add the amount you ( and we ) are seeing.

**Comment by JorgenEvens** [comment]
Did some digging and I was not experiencing slow rendering templates, but had some other code that ran right before it being slow.

That being said, if you could share a template on which you are experiencing slow rendering I'd be happy to have a look.

**Comment by DrParanoia** [comment]
Hi there! Sorry for the wait. I think your test case is too simple to see the issue. I've just tested your commit but the issue is still there. I've used this code just for testing purposes.

```
var template = "{{ echo_test }}\
{% for item in items %}\
    <h1>{{ item.title }}</h1>\
    {% if item.is_active %}\
        <h3 style=\"color: green;\">Active</h3>\
    {% else %}\
        <h3 style=\"color: red;\">Inactive</h3>\
    {% endif %}\
{% endfor %}";

console.time('twig');
for(var i = 0; i < 1000; i++) {
    Twig.twig({
        data: template
    }).render({ 
        echo_test: 'Data for echo',
        items: [
            {
                title: "This is a title",
                is_active: true
            },
            {
                title: "This is a title",
                is_active: false
            }
        ] 
    });
}
console.timeEnd('twig');
```

Your branch produces the result of roughly 340ms for me in Chrome console.
The old branch finishes the test in roughly 214ms.

The difference can be even bigger if the template is more complex or if there are more iterations.

Thanks!

**Comment by willrowe** [comment]
It seems to me this would be an issue with the browser optimization of Promises. I'm not even sure if this is still an issue at this point, but if anyone can find something that is being done wrong in the twig.js code itself that is causing a slowdown, that is the only thing that could be done from this end.
