### ISSUE TITLE
Support ternary without ":" operator

### ISSUE THREAD

**Issue by derekderaps** [twigjs/twig.js#476]
PHP Twig supports ternary syntax without the `:` (colon). This:
```
{{ foo ? 'bar' }}
```
is equivalent to this:
```
{{ foo ? 'bar' : '' }}
```
We ran into this while trying to use KSS to compile a modified version of the Drupal 8 Classy theme's main menu template, which includes a ternary with this syntax.

**Comment by wojtas** [comment]
The current behavior can cause hard to spot errors, if you use twigjs for some already working templates in the PHP version and don't review them thoroughly, leaving the simplified ternary condition syntax occurences in place. For example

`{{ false ? 'true' }}`

currently yields true, which is obviously wrong. If it's unsupported, maybe it could raise an error.

It is also important to remember the second supported syntax, which is

`{{ false ?: 'false' }} => equivalent to {{ false ? '' : 'false' }}`

and should also be implemented if the first one is.

If I have time I might look further into this and maybe provide a necessary fix.

**Comment by olets** [comment]
@derekderaps what behavior are you seeing?

@wojtas are you on the latest version?

I'm getting, `{{ x ? 0 }}` compiling to `0`, and

```twig
{% set x = 1 %}
{{ x ? 0 }}
```

compiling to `1`.

To wojitas's point, I'm also getting `{{ x ?: 0 }}` compiling to `0`.

**Comment by derekderaps** [comment]
My understanding is that this:
```twig
{{ x ? 0 }}
```
is equivalent to this:
```twig
{{ x ? 0 : '' }}
```
and should therefore evaluate to `''` (empty string, since `x` is undefined), while this:
```twig
{% set x = 1 %}
{{ x ? 0 }}
```
would evaluate to `0`, since `x` is defined and truthy.

On the second part, note a difference to the equivalence posted by @wojtas; the [relevant Twig docs](https://twig.sensiolabs.org/doc/2.x/templates.html#other-operators) say this:
```twig
{{ foo ?: 'no' }} is the same as {{ foo ? foo : 'no' }}
```
Either way, `{{ x ?: 0 }}` compiling to 0 is the correct behaviour when `x` is undefined.

**Comment by olets** [comment]
@derekderaps sorry I don't know how I managed to typo that that badly.

Your understanding is right _and_ that's what I'm getting. What I meant to say is that for me

- `{{ x ? 0 }}` (with `x` undefined) compiles to an empty string
- `{% set x = 1 %}{{ x ? 0 }}` compiles to `0`

For the second part I managed to say what I meant: `{{ x ?: 0 }}` (with `x` undefined) is giving me `0`. I'll add that `{% set x = 1 %}{{ x ?: 0 }}` is giving me `1`

Are you using twig.js directly?

**Comment by derekderaps** [comment]
@olets Oh okay great, I'll double-check what I'm getting now and let you know, I haven't tried since the original post.

**Comment by olets** [comment]
Any update on this?

**Comment by derekderaps** [comment]
Heya @olets, thanks for the bump. Yup, everything is working as expected! Not sure if I was just confused or if support was added since May. Anywho, thanks, @olets, I believe we are good to go here! Closing...
