### ISSUE TITLE
Using Express 4 

### ISSUE THREAD

**Issue by francesco2you** [twigjs/twig.js#477]
I open this repo on and just copy the entire code  _for usign with express_ and past it, and for my surprise does·n't work.
So the issue is that i'm using express 4 and copy a boilerplate for the express 3...

Please, consider include something like that on readme...
```javascript
var express = require('express'),
    app = express();

// Set engine like that
app.set('view engine', 'twig')

// Default express views folder is views, bu we can change like that 
app.settings.views = 'your_views_dir';

// Render example (just like olders)
app.get('/', function(req, res){
    res.render('home', {
        message : "Hello World"
    });
});

// Listener
app.listen(9999);
```

**Comment by Stinobe** [comment]
I'm using Express 4.15.2 and managed to implement Twig.js without any issue, just by using it as described on README.

I think the biggest problem is you're not loading the Twig package.
```
const Twig = require( 'twig' );
```

This is what I have
```es6
// NPM Packages
const express = require( 'express' ),
      {twig}  = require( 'twig' );   // Destructing Twig since I only need Twig.twig

// Express instance
const app = express();

// Set render engine
app.set( 'view engine', 'twig' );

// Render a template
app.get( '/', (req, res) => {
  res.render( 'template',  {
    data: "This is just some data"
  });
});
```
> You could make it shorter by using `const app = require( 'express' )();` and leave out
`const app = express();`

**Comment by francesco2you** [comment]
I'm see that.
