### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Stinobe** [twigjs/twig.js#479]
First of all: __Great Job__
I'm using this package in every single project!

I was wondering if there's any way to improve the documentation on extending Twig.js. I know there's a WiKi but sometimes it's pretty hard to figure out which function, variable, ... is doing what.

**Comment by francesco2you** [comment]
You can fork it, and do(/try) what you want.

**Comment by olets** [comment]
You might also be looking for https://twig.sensiolabs.org/doc/2.x/advanced.html but don't hesitate to contribute!
