### ISSUE TITLE
date function not working in template

### ISSUE THREAD

**Issue by Johnb21** [twigjs/twig.js#485]
Attempting to load ONLY the 4 digit year within the template is not working. I have tried the following:

```<span>&copy; {{ date('Y') }}</span>```

AND 

```<span>&copy; {{ date('Y', 'now') }}</span>```

Both of these are returning

Wed Dec 31 1969 19:00:00 GMT-0500 (EST)

Desired Output: 2017

**Comment by philsbury** [comment]
Hi @Johnb21,

Date is a filter, so try `{{ now|date('Y') }}`

https://twig.sensiolabs.org/doc/2.x/filters/date.html

**Comment by Johnb21** [comment]
@philsbury - that worked. Thanks!!
