### ISSUE TITLE
How to properly include, block, extends and pass variables?

### ISSUE THREAD

**Issue by Extarys** [twigjs/twig.js#489]
How can I achieve this in twigjs?
I managed it well in php but on js I'm stuck.

base.twig
```
<body>
<div>
    {{ include partial1 }}
</div>
<section>
<h1>title</h1>
    {% block content %}{% endblock %}
```
index.twig

```
{% extends "base.twig" %}
<div>
    {{ include partial1 }}
</div>
   {% block side %}
    {{ parent() }}
OMG - exclusive index sidebar content
{% endblock %}
```
Also how can I pass variables to 'include' or 'block' ?

App call 'base' with var1:50 -> base call head, pass var1

**Comment by Neirda24** [comment]
I am not sure as I didn't test it but: when you extend you should always declare in block sections. Even in PHP I think.

**Comment by ScoutsOut** [comment]
Did you ever figure this out?

**Comment by ericmorand** [comment]
The template in the first post is not valid.

But to pass variable to an included template, use the `with `keyword:

`{% include "foo.twig" with {foo: 'bar'} %}`

You can't pass variables to block, that doesn't make sense.
