### ISSUE TITLE
Assets support

### ISSUE THREAD

**Issue by cancinos** [twigjs/twig.js#499]
I'm trying to include a simple image to a div tag on my twig template but I want to know if there is any workaround for the unsupported function **asset**. 

I'm not using Express, so I'm rendering my templates with the following code:

```javascript
Twig.renderFile('./path/to/someFile.twig', data, (err, html) => {
  html; // compiled string
});
```

Thanks in advance!

**Comment by willrowe** [comment]
Which asset function are you referring to?

**Comment by cancinos** [comment]
I'm referring to [this](https://symfony.com/doc/current/assetic/asset_management.html#introducing-assetic). I want to define and access to an image asset, but I don't know how to implement it with twig.js, and also I look for your [features support](https://github.com/twigjs/twig.js/wiki/Implementation-Notes#feature-support) and I didn't find this asset functionality. Do you have any clue about it?

**Comment by cancinos** [comment]
I understand; so just for make things clear for me, the only way I have to show a image on my template is referring it with the relative or absolute path, am I right?

**Comment by willrowe** [comment]
Yes, you need to use the actual path.

**Comment by cancinos** [comment]
Thanks for your help! I'll do it with that.

**Comment by olets** [comment]
@cancinos to clarify in case you run into this again: Twig.js is a js implementation of the template language Twig (https://twig.symfony.com/doc/2.x/, https://github.com/twigphp/Twig) not of the framework Symfony (https://symfony.com/, https://github.com/symfony/symfony)

**Comment by cancinos** [comment]
Thanks for the explanation. I'm using it in a RabbitMQ's mail send queue! I found it really useful for my various templates! @olets
