### ISSUE TITLE
Request {% with %} tag for nested scoping

### ISSUE THREAD

**Issue by xiuda** [twigjs/twig.js#502]
twig 1.28.0 implemented the [with tag](https://github.com/twigphp/Twig/blob/v1.28.0/CHANGELOG)  which would be incredibly useful for nested scoping.

Links:
- https://github.com/twigphp/Twig/blob/2.x/lib/Twig/TokenParser/With.php
- https://github.com/twigphp/Twig/tree/2.x/test/Twig/Tests/Fixtures/tags/with

**Comment by dave-irvine** [comment]
Added in https://github.com/twigjs/twig.js/pull/497
