### ISSUE TITLE
multiple template paths

### ISSUE THREAD

**Issue by brunocasado** [twigjs/twig.js#503]
Hi guys,

I have two apps in node js + express where the first is the application core, with default views.

I do an import the second app to the inside of first app ( app.use(app2) )

With jade, even if the second app dont have the view, he got the view from the app one. 

The problem: When i import two apps with twig engine i got this message:

```
TwigException: Unable to find template file /home/**/projects/***/****/views,/home/**/projects/catalog_v2/views/layout.html
Program node bin/www exited with code 1
```

Question, how i can use two apps with twig?

app1.js

```
var app = express();
app.use(vhosts(app)); // app1
// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'html');
app.engine('html', twig.__express);
```

app2.js ( same config, less vhosts )

```
var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'html');
app.engine('html', twig.__express);
```

thanks!

**Comment by olets** [comment]
Have you read through the [Express 2 example](https://github.com/twigjs/twig.js/wiki/Express-2)? Your setup is different but that is a good place to start

**Comment by brunocasado** [comment]
@olets i used the express 3 custom extension sample. ( because i use .html files )

the strange is that i cant use two apps with the same twig engine.
