### ISSUE TITLE
Twig and node

### ISSUE THREAD

**Issue by isvaljek** [twigjs/twig.js#504]
I have a relatively simple node app that uses Twig as the template engine.
The problem is that the whole logic up to the app.render takes 10-15 ms(including DB calls), and then it takes 35-50 ms for the template to render. The resulting html is about 100 KB large, and I don't know if the input JSON object's size matter (I guess I can trim him down). 
This is more a cry for advice or optimization tips than an issue report, but I didn't know where to turn to.

**Comment by dave-irvine** [comment]
To be honest, twig.js is fairly slow. @olets has probably used the project the most so he will be your best bet for optimisation tips, but yes we need a lot of work on improving the template render speed.

**Comment by olets** [comment]
No optimization tips here, sorry. My use is mostly with gulp-twig for static site development and local development of (non-static) Twig sites... That delay isn’t something I’d notice in my workflow and especially with a cacheing layer it wouldn’t be a limiting factor for my final product. I'm impressed that is noticeable in your app!

In browserland 100k would be a really heavy site... I wonder if it's possible to cut that down? That doesn't address your twig.js question but it might help your speed.

Give #492 a try. That work was tested on tasks 10x slower than yours.. it would be cool to know if it makes a difference at your speed or if you're at a threshold. 

And of course, of you're into optimizing js contributions are welcome!

**Comment by dave-irvine** [comment]
There have been several performance improvements in recent releases. Please try again and if the problem persists, let us know.
