### ISSUE TITLE
Ternary operator does not work with arrays

### ISSUE THREAD

**Issue by 4nduril** [twigjs/twig.js#507]
Hello, thank you for your work of bringing Twig to JavaScript.
However, I have found the following issue (minimal example):
```javascript
const template1 = twig.twig({
  data: '{{ (true ? ["yay"] : ["nay"])[0] }}'
});
template.render();
// ''
```
If the condition is `false` it works:
```javascript
const template2 = twig.twig({
  data: '{{ (false ? ["yay"] : ["nay"])[0] }}'
});
template.render();
// 'nay'
```
With strings instead of arrays it works as expected. When I tried it with Twigfiddle (https://twigfiddle.com/ldwyfk) it also worked fine with arrays, so I think it is a problem with Twigjs.
Changing from ternary to if/else also works.

**Comment by isthatcentered** [comment]
Yep, same for me, here are a few more infos:
```twig

{# classes defined as arr #}
{% set classes = ["waffles", "are-the-best"] %}
{{ classes ?: "nope" }} {# // -> 2 #}
{{ classes ? classes : "nope" }} {# // -> 2 #}
{{ classes ? "yep" }} {# // -> "yep" #}

{# classes defined as string #}
{% set classes = "Anyone seen Robin?" %}
{{ classes ?: "nope" }} {# // -> "Anyone seen Robin?" #}
{{ classes ? classes : "nope" }} {# // -> "Anyone seen Robin?" #}
{{ classes ? "yep" }} {# // -> "yep" #}

{# classes null #}
{% set classes = null %}
{{ classes ?: "nope" }} {# // -> "nope" #}
{{ classes ? classes : "nope" }} {# // -> "nope" #}
{{ classes ? "yep" }} {# // -> "" #}
```

A good fallback while waiting for fix is the [default filter](https://twig.symfony.com/doc/2.x/filters/default.html)
```twig
{% set _classes = [ 
        "stuff" 
   ] | merge( overrides | default( [ "iWontThrowNow", "andIhaveMyFallback" ] ) ) %}
```

**Comment by Kingdutch** [comment]
This could be considered a different issue but it also doesn't work in arrays:
```
{% set classes = [
  'some_class',
  condition ? 'other_class'
%}
```

If `condition` equals `'x'` then `classes` will be set to `['some_class', 'x']` whereas it would be expected to equal `['some_class', 'other_class']`

**Comment by arismag** [comment]
Is there any update on this issue? Especially regarding @Kingdutch comment.

A temp workaround is this one, but is not really satisfiable:
```
{% set modifiers = [
  isDark ? 'c-card--is-dark' : '',
  hasMedia ? 'c-card--has-media' : ''
] %}
```

**Comment by codebymikey** [comment]
Ternaries are still broken in the latest version of the repo.

The following crashes the parser.
```twig
{# This breaks the parser. #}
{%
  set classes = [
    title_display == 'after' ? 'option',
    title_display == 'invisible' ? 'visually-hidden',
    required ? 'js-form-required',
    required ? 'form-required',
    'form-label',
  ]
%}
```

However wrapping the first ternary array entry in a bracket fixes it.
```twig
{# No longer breaks the parser. #}
{%
  set classes = [
    (title_display == 'after' ? 'option'),
    title_display == 'invisible' ? 'visually-hidden',
    required ? 'js-form-required',
    required ? 'form-required',
    'form-label',
  ]
%}
```

**Comment by codebymikey** [comment]
For others having issues with twig.js's parser issues, you're better off using [Twing](https://github.com/NightlyCommit/twing). It's a more stable twig implementation.

**Comment by willrowe** [comment]
The original example provided by @4nduril works in the latest version which can be [seen here](https://codepen.io/willrowe/pen/RwMaPZR).

As for the other ternary examples given, no simple and clear example was provided, so it's hard to determine which one wasn't working. If there are still issues with those other cases, please open a new issue with a simple example that works on TwigFiddle and the same example not working using [this template](https://codepen.io/pen?template=LYQawea).

**Comment by Kingdutch** [comment]
I see I missed a closing square bracket in my previous example.

Twig fiddle shows that that case now works as expected: https://twigfiddle.com/roz6mz
