### ISSUE TITLE
requireJS compatibility?

### ISSUE THREAD

**Issue by smcjones** [twigjs/twig.js#511]
Hello, this may be a very stupid question and a non-issue... However, is this meant to be requirejs compatible? I see it is AMD compatible. However, the two dependencies, "fs" and "path" are not included in the package nor are they declared dependencies. 

Any help would be appreciated, as right now this makes twigjs unusable with requirejs.

Thanks,

Sean

**Comment by smcjones** [comment]
As a quick followup, I am quite certain that "fs" and "path" refer to node packages, which tells me that this may not be requireJS compatible at all after all?

**Comment by dave-irvine** [comment]
It should work in requirejs, just stub `fs` and `path` to null.

**Comment by smcjones** [comment]
Thanks! Works perfectly.
