### ISSUE TITLE
json_encode object containing a date results in empty object for date

### ISSUE THREAD

**Issue by petbo2** [twigjs/twig.js#514]
Hi,
When running an object which contains a date value through the json_encode filter, the resultant JSON 'loses' the date (replacing with empty object).

Example:
`const testObj = {
a: 1,
b: new Date()
}`

`{{testObj|json_encode}}`

Result:
`{"a":1,"b":{}}`

What I'd expect:
`{"a":1,"b":"2017-12-13T12:47:26.838Z"}`

I believe this is because the json_encode filter function is using Object.keys() on the date object to stringify it, which returns an empty array.

A workaround:
`Twig.extendFilter("native_json_encode", (value) => JSON.stringify(value));`
`{{testObj|native_json_encode}}`

I'm sure there's a good reason why a custom JSON stringify-ing method is used by Twig rather than the native JSON.stringify (maybe browser support?). Otherwise I'd submit a pull request replacing the custom function with the above.

**Comment by dave-irvine** [comment]
I think the function here: https://github.com/twigjs/twig.js/blob/master/src/twig.filters.js#L184 just needs an extra case to test if the `value` is a Date. Feel free to write a PR :)

**Comment by petbo2** [comment]
PR submitted!
