### ISSUE TITLE
add Twig.addGlobal like in the PHP version

### ISSUE THREAD

**Issue by jaysee** [twigjs/twig.js#521]
Hello,

Handling this like in the PHP version the $twig->addGlobal method to allow us to create some more complex helpers than Twig.extendFunction. (or allow Twig.extendFunction to handle object as second argument)

regards,

**Comment by willrowe** [comment]
Closing this due to lack of details. If you would like to provide an example of how you would you can extend TwigPHP, but can't currently accomplish the same thing with twig.js, please re-open this issue.
