### ISSUE TITLE
working with Pimcore CMS and webpack 

### ISSUE THREAD

**Issue by izulfi** [twigjs/twig.js#522]
Hi John,

I just tried to make workaround for [Pimcore 5 CMS](https://pimcore.com/docs/5.0.x/Development_Documentation/MVC/Template/Twig.html) with webpack and it look like is going to work after some small fixes in twig.core.js. 
I found out that, if I comment out line 963 (validating twig ID) is going to work. Can you make some improvements in your excellent Work to make some Workaround to get work with [Pimcore 5 CMS ](https://pimcore.com/docs/5.0.x/Development_Documentation/MVC/Template/Twig.html)using twig templating?

Thank you.

**Comment by olets** [comment]
As a workaround for now, does https://github.com/Hagith/pimcore-boilerplate meet your needs? I haven't used it, but it claims to be a Primcore dev environment with webpack

**Comment by dave-irvine** [comment]
No feedback from reporter, gonna close.
