### ISSUE TITLE
New related project: Twing is Twig in TypeScript, with full Twig support! Contributions welcome!

### ISSUE THREAD

**Issue by ericmorand** [twigjs/twig.js#528]
Hi,

Some months ago I tried to make some improvements to twig.js because I was using it to compile Drupal 8 templates and the lack of some of the official syntax was making them impossible to build - and I'm not even talking about https://github.com/twigjs/twig.js/issues/519

I quickly discovered that the architecture and philosophy behind twig.js made implementing Twig specifications impossible without having to rewrite some huge part of the source code. This plus the fact that I also wanted to add source-map support and I came to the conclusion that it was not worth it.

I then took the decision to write my own implementation of Twig and to not make the same mistakes. In other words, I wanted to have the code architeture as close as possible to TwigPHP. After all, since TwigPHP implements Twig specifications perfectly, transpiling it to JavaScript would lead to the same perfect result.

Obviously, all was not as easy as I hoped but it was far way easier than I feared!

And today, twing is alive:

https://github.com/ericmorand/twing

Twing uses the exact same API as TwigPHP, the exact same philosophy (lexer, parser, compiler, node visitors, extensions, loaders, cache systems and much more, everything is there) and nearly the same classes architecture - there are a few classes and helpers added to ease code readability since TypeScript is more strongly typed than PHP and to implement PHP behaviors when they differ from JS ones.

Twing support ALL the official Twig specifications and this is supported by an integration test suite that is that _exact_ replica of the TwigPHP integration test suite. And since the source code is basically a transpilation of TwigPHP to TypeScript, adding support for eventual new syntax is trivial. Even better: any feature added to Twing (I think source-map support that I plan to add quickly) can be backported to TwigPHP with close to zero effort.

Icing on the cake: since the API is exactly the same, TwigPHP documentation applies. And things that may not apply will be fixed to apply.

So, if you think twig.js is missing things for your needs, feel free to have a look at Twing. I'm sure you'll like it.

**Comment by deflock** [comment]
Not sure this is the right place to announce it, but looks interesting.
Any benchmarks comparing twigjs vs twing?

**Comment by ericmorand** [comment]
@deflock there is no need for benchmark: Twing is probably way slower right now. :D  Zero effort has been made on performance. It will be improved in the future but the prime focus was maintainability and specification accordance.

**Comment by olets** [comment]
To visitors of the Twig.js issues page this issue's title could read like an explicit endorsement or a deprecation notice. Thoughts about renaming the issue?

///

I see you're at 39% coverage. What's the story with that?

> lack of some of the official syntax…and I'm not even talking about \[glitchy `embed` support]

If you remember any problems you had that aren't documented in issues here, please write them up. We appreciate it!

> After all, since TwigPHP implements Twig specifications perfectly

TwigPHP _is_ Twig, it'd be impossible for it not to ;)

> Twing uses the exact same API as TwigPHP, the exact same philosophy…and nearly the same classes architecture

Very cool.

> any feature added to Twing can be backported to TwigPHP with close to zero effort.

Well, into a fork at least :) Fabien is pretty particular about what gets into Twig

> Twing

Do what you want of course, and yours isn't the first Twig port to not include "twig" in the name, but I'd be careful about porting an established project and giving it a name that makes it sound like something new.

Overall, and interesting project :+1: I'll be interested to see how it develops

**Comment by ericmorand** [comment]
> To visitors of the Twig.js issues page this issue's title could read like an explicit endorsement or a deprecation notice. Thoughts about renaming the issue?

I spent some long minutes figuring a title for this issue that would not make it something that is it not. I'm not satisfied with this one and I would take advices with great pleasure. The point here is that I've used twigjs for years and I still love it for all the great things it did and still does. But I feel it's now dated. I don't want this issue to feel like anything else.

> I see you're at 39% coverage. What's the story with that?

Yes, it's low and it's the focus for the v1.0. The thing is a lot of code is called by the template when it is rendered and since the rendering is "defferred" like in TwigPHP, these lines of code are not coverable by integration tests. I have to implement the unit test suite of TwigPHP to increase the coverage.

Once again, the focus there was specification accordance, i.e. integration tests. Now that this part is done, I'll focus on unit tests.

> TwigPHP is Twig, it'd be impossible for it not to ;)

I love to think that Twig is the specs and TwigPHP the reference implementation.

> Well, into a fork at least :) Fabien is pretty particular about what gets into Twig

Hahaha, yes, I've witnessed that.

> Do what you want of course, and yours isn't the first Twig port to not include "twig" in the name, but I'd be careful about porting an established project and giving it a name that makes it sound like something new.

We'll see. I've tried to contact Fabien about this - name and copyrighting issues. Still waiting for his answer. Once again I don't want Twing to look like something else that what it is: basically a transpilation of TwigPHP.

**Comment by olets** [comment]
Cool. Maybe something like "new related project: twing is twig in typescript. contributions welcome!". Can't speak for the other members, but with a title like that I'd be cool leaving the issue open to encourage people to check it out… maybe it'll help the shared goal of a perfect js twig!

**Comment by ericmorand** [comment]
Well now that's a great title. I'll borrow it as-is if you don't mind.

**Comment by ericmorand** [comment]
@dave-irvine, that's so super nice from you to have added Twing as an alternative in the README.

**Comment by MickL** [comment]
@ericmorand 

- What is the difference between `https://github.com/ericmorand/twing` and `https://github.com/NightlyCommit/twing`? 
- Why doenst `https://github.com/ericmorand/twing` have an issue tracker?
- What is the status of the project in terms of coverage and performance?
- Is the performance better than `twigjs/twig.js`?

**Comment by ericmorand** [comment]
@MickL ,

The first repository is my own personal fork. The second one is the official one. Your question raises a fair point though. I should make it clear that the first one is a personal fork.

Specifications coverage is 100% as of Twig 2.11. And code coverage is 100% too. The project is actively maintained both from bugs and features point of view.

Performance are better than twig.js. I have to update the official benchmark with Twig 4 which brought async support and then slower performance. Still, it is way faster than twig.js from my preliminary testings.

**Comment by MickL** [comment]
@ericmorand Why didnt you post the official one? Why dont you contribute to the official one?

**Comment by ericmorand** [comment]
Because I consider myself as a contributor like any other and use the same fork + PR process. I use my own fork to test features, push work in progress commits that I squash eventually.

**Comment by PolyPik** [comment]
@ericmorand I have returned from the Shadowrealm. >:D

Anyways, twigjs still has the advantage of being way smaller in terms of filesize.

**Comment by ericmorand** [comment]
@PolyPik, absolutely. It would be interesting to compare the size of both bundles with the same features though. I suspect twig.js would still be smaller but not by a huge margin.

**Comment by olets** [comment]
Now I'm confused too. Thought you'd just moved it under the NightlyCommit org. So ericmorand/twing is essentially the development branch of NightlyCommit/twing?
