### ISSUE TITLE
Custom tag loses context in imported template

### ISSUE THREAD

**Issue by KulakovSerg** [twigjs/twig.js#529]
My purpose is temporary render old php-simphony twig pages in nodejs while react templates refactoring is not finished (a lot of pages and more then 10 locales).
I have try to use custom tag example and it works fine with my %trans% tag, but when I tryed asynchronously render all templates, there is a bug: translation language key-value object I pass in context argument to twig.render is undefimed inside any imported part. It seems context is lost while import.
I tryed to do the same thing with custom tag declaratuon scope, but it is impossible because custom tag and all its functions is global and override all rendering templates - the same language is everywhere

**Comment by willrowe** [comment]
Closing due to lack of example code. If you are still encountering this issue and would like to provide a simple example using [this template](https://codepen.io/pen?template=LYQawea), please re-open this issue.
