### ISSUE TITLE
Version not incrementing after release 0.10.2

### ISSUE THREAD

**Issue by jeremygrajales** [twigjs/twig.js#535]
It seems that although I have installed later versions of this package, the version ID in the compiled webpack still shows 0.10.2.

For example, shouldn't this be set to 1.10.5?
https://github.com/twigjs/twig.js/blob/v1.10.5/src/twig.js#L10

This seems to be the case beginning with the 0.10.3 release.

**Comment by dave-irvine** [comment]
Resolved
