### ISSUE TITLE
Idea: Bundle a version of Twig.js without template compilation

### ISSUE THREAD

**Issue by mortenson** [twigjs/twig.js#543]
The current `twig.min.js` file is ~84k, which is quite large for a client side library.

I was thinking of ways to reduce this, and was wondering if we could also ship a version of Twig.js that has no template compilation, and only includes the `Twig.*` methods that compiled templates call.

This may seem counter-intuitive, but for users of the Webpack loader [twig-loader](https://github.com/zimmo-be/twig-loader) all Twig templates are already pre-compiled, which means that the client will never need any of the compilation code included in `twig.min.js`.

I think that removing `twig.compiler.js` and `twig.expression.js` from a new output file like `twig.nocompile.min.js` could remove at least 20k of code, and that's just at a first pass. For performance reasons, I don't think there's a good reason to have clients compile templates unless they absolutely have to.

Thoughts?

**Comment by dave-irvine** [comment]
Sounds like https://github.com/twigjs/twig.js/issues/530 and https://github.com/twigjs/twig.js/issues/80 ?

**Comment by mortenson** [comment]
@dave-irvine Yep, sounds like #530 basically covers it. I guess I was using the wrong keywords 😄 
I'll close this out.
