### ISSUE TITLE
Unexpected regression in kss-node from twig 1.11.0

### ISSUE THREAD

**Issue by ryuran** [twigjs/twig.js#545]
I have an unexpected regression in Kss-node project since twig.js 1.11.0.

Include of relative path are not correctly resolved.
https://github.com/kss-node/kss-node/issues/467

I don’t see relative notice about that in twig.js changelog.

**Comment by dave-irvine** [comment]
Probably https://github.com/twigjs/twig.js/pull/492 ?

**Comment by ryuran** [comment]
@dave-irvine probably.
@JorgenEvens do you have an idea ?

**Comment by JorgenEvens** [comment]
@dave-irvine @ryuran Will have a look later this evening

**Comment by ryuran** [comment]
@JorgenEvensn did you find anything to help about it?

**Comment by JorgenEvens** [comment]
@ryuran Sorry, forgot about this. I've put it on my todo for tonight

**Comment by JorgenEvens** [comment]
@ryuran I'm going to need more information or a specific testcase. I've added a test that includes a file relative to another and it resolves the file as expected.

See https://github.com/twigjs/twig.js/pull/552

**Comment by ryuran** [comment]
I have try with v1.12.0 and the problem seems solved. I don’t know what fixed it.
