### ISSUE TITLE
Inline HTML templates

### ISSUE THREAD

**Issue by isvaljek** [twigjs/twig.js#549]
Is it possible to create/load <script id="mytemplate" type="text/template"> for twig templates?
I'd like to minimize ajax calls, I have way too much chatter.

**Comment by Neptuli** [comment]
hi isvaljek,

what server side script do you use?
With PHP and TWIG (server side) you can make a <script></script> Tag with the inline template!

**Example**
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
var template = twig({
    id: "tweets",
    data:  {{ include('') }}  //Template
});
</script>
<script src="localhost/own/jquery/file"></script>
</head>

...........
</html>

**Example own Jquery**
$(document).ready(function () {

var output = twig({ ref: "tweets" }).render({
    list: ["a", "b", "c"]
});

});


best regards

**Comment by willrowe** [comment]
Another approach that I often use is to pass a list of templates to a partial like so:
```twig
<script type="text/javascript">
    (function () {
        window.addEventListener('DOMContentLoaded', function () {
            {% set compiled_paths = [] %}
            {% for template in templates %}
                {% if template.path not in compiled_paths %}
                    if (Twig.twig({'ref': {{ template.path | json_encode }}}) === null) {
                        Twig.twig({
                            allowInlineIncludes: {{ template.allowInlineIncludes | default(false) | json_encode }},
                            data: {{ source(template.path) | json_encode }},
                            id: {{ template.path | json_encode }}
                        });
                    }
                    {% set compiled_paths = compiled_paths | merge([template.path]) %}
                {% endif %}
            {% endfor %}
        });
    }) ();
</script>
```

The structure of the context would be like so:
```json
{
    "templates": [
        {
            "path": "path/to/template.html.twig"
        }
    ]
}
```

**Comment by dave-irvine** [comment]
Solutions offered, no feedback from reporter.

**Comment by isvaljek** [comment]
Thanks for answering guys, I just got reminded about this one. I like the approach, but I have one more hurdle: I'm using an ajaxified site which re-renders everything from the id="wrapper" downwards (on page load). The side effect is that a lot of partial templates load via include xhr functions, so until all partials settle in the browser cache I get a lot of chatter between the browser an the server. I'm not sure if your example allows me to override this behaviour. How to tell the twig's include function to include the preloaded template instead of asking the server?

**Comment by Neptuli** [comment]
Hi isvaljek!

The only different between a server side solution and a client side solution, is that you get by the client side solution json responses from the server  (less download time)!

I don't think that there is a setting (in twig), where you can say -> cache first! The only way is do make your own cache functions, with javascript / jquery -> but care of the size! 

If you want a offline database on the client side, you need do make a web application with service-worker and a manifest.json -> https://developers.google.com/web/ilt/pwa/

Do you have a link. for the website -> so i can look how many xhr request you make (maybe I can help you better)?

best regards

**Comment by isvaljek** [comment]
If anyone else looks for anti-ajax treatment (for loading included twig templates), look here:
https://www.npmjs.com/package/twig-loader
