### ISSUE TITLE
TwigException: You are using Twig.js in sync mode in combination with async extensions

### ISSUE THREAD

**Issue by alandwiprasetyo** [twigjs/twig.js#553]
Hi, i have found error 

"TwigException: You are using Twig.js in sync mode in combination with async extensions."

I use sequalize for ORM, and i will show data table many to one
![screen shot 2018-05-17 at 12 56 47 am](https://user-images.githubusercontent.com/10112729/40134631-38ba915c-596d-11e8-8f96-eb31360a87b7.png)

How to solved this probem? and how to set async extensions in express 3?

**Comment by JorgenEvens** [comment]
Hi @alandwiprasetyo ,

You can now use async rendering in combination with the `express` renderer by enabling the `allow_async` option. See [the example](https://github.com/twigjs/twig.js#appjs) in the readme.

**Comment by theobouwman** [comment]
Does not work for me. Using twig 4+
