### ISSUE TITLE
date formatter is create timezone difference with Node server

### ISSUE THREAD

**Issue by alxpereira** [twigjs/twig.js#557]
Hello, 

I've encountered an issue on the date formatting recently. 
The *variable|date('H:i')* formatting for example is working properly on my localhost (the date is well rendered on the right timezone). 

However on a distance server (AWS Ireland), I'm having a logical but un-explainable 2hours difference without any code change. 
I've managed to manually correct the anomaly with a date_modify, however that won't be the best solution. 

Any idea ? 

Thanks
Alex

**Comment by toptalo** [comment]
Check your AWS config timezone

**Comment by willrowe** [comment]
Fixed by #566.
