### ISSUE TITLE
Date function doesn't escape sequences

### ISSUE THREAD

**Issue by Garbee** [twigjs/twig.js#563]
Problem:

The date function should allow for an escape sequence to have text put inside of the output. This is documented in [twig from sensio](https://twig.symfony.com/doc/2.x/filters/date.html).

> To escape words and characters in the date format use \\ in front of each character:
> `{{ post.published_at|date("F jS \\a\\t g:ia") }}`

Solution:

Allow for some kind of escape sequence. Even if `\\` isn't allowed for some technical reason; find a sequence that can be allowed and document that it is available.

**Comment by toptalo** [comment]
This future work well. You need to use `\\` before each character you wont to escape:
`{{ "Tue Aug 14 08:52:15 +0000 2007"|date("F jS \\a\\t g:ia") }}` -> `August 14th at 12:52pm`
`\\a\\t` -> `at` 

Or I misunderstood your question?

**Comment by toptalo** [comment]
Wow. If I try to do that in tests - it works well, but it broken in templates

**Comment by Garbee** [comment]
Yes `\\` before a character to escape. As documented in the sensio docs for the filter. This allows us to form more textual date outputs.

On only being broken in templates... perhaps that means the parser of templates is doing something to modify the expected input to the function.

**Comment by willrowe** [comment]
Where exactly are you encountering this issue? I'm not sure what you mean by it being "broken in templates". Please provide a way that the issue can be reproduced.

**Comment by toptalo** [comment]
This works:
```
it("should escape words and characters in the date format [twig({data})]", function () {
    var template = twig({data: '{{ "Tue Aug 14 08:52:15 +0000 2007"|date("F jS \\a\\t g:ia") }}'});

    template.render().should.equal( "August 14th at 12:52pm" );
});
```
This fails:
```
it("should escape words and characters in the date format [twig({ref})", function () {
    twig({
        id: 'escape-date-format',
        path: 'test/templates/escape-date-format.twig',
        async: false
    });

    // Load the template
    twig({ref: 'escape-date-format'}).render({}).should.equal("August 14th at 12:52pm");
});
```

**Comment by toptalo** [comment]
Hmmm
If I change `escape-date-format.twig` to

```
{{ "Tue Aug 14 08:52:15 +0000 2007"|date("F jS \a\t g:ia") }}
```

Tests pass

**Comment by Garbee** [comment]
Closing since the PR to fix has been merged.
