### ISSUE TITLE
global is not defined 

### ISSUE THREAD

**Issue by zwarmapapa** [twigjs/twig.js#565]
Since 1.12.0 I'm getting an error stating: "ReferenceError: global is not defined"

The error points to here:

!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.Twig=t():e.Twig=t()}(**global**,function(){return function(e){var t={};function

1.11.0 and older versions do work.

**Comment by zwarmapapa** [comment]
I made a workaround for it by adding this all the way on the top of my javascript:

if(typeof window.global === "undefined"){ window.global = window; }

Not certain if this is expected.

**Comment by dave-irvine** [comment]
@zwarmapapa I guess you are using Twig in the browser?

**Comment by zwarmapapa** [comment]
Yes I am using it in the browser. Is global a NodeJS thing? (I have zero experience with NodeJS)

**Comment by dave-irvine** [comment]
@zwarmapapa try using twig.min.js from that package and see if it works

**Comment by dave-irvine** [comment]
Ah yes you mentioned it:

> Also, notice that the non-minified versions are also minified, but the code in the minified vs the non-minified one is different (the minified one has "window" instead of "global" for example).

So really, 'twig.min.js' is more accurately named: 'twig.browser.js', and 'twig.js' would be more accurately 'twig.node.js'.

**Comment by zwarmapapa** [comment]
Oooh that explains it. Thanks!
