### ISSUE TITLE
RAW filter didn't working!!!

### ISSUE THREAD

**Issue by IftekherSunny** [twigjs/twig.js#571]
Any reason doesn't support for RAW filter???

**Comment by dave-irvine** [comment]
The reason is it hasn't been implemented yet.

**Comment by IftekherSunny** [comment]
implement it bro :(

**Comment by dave-irvine** [comment]
I look forward to your pull request :)

**Comment by toptalo** [comment]
As I see templates rendered as raw by default, because template block `{% autoescape %}` hasn't been implemented yet. Do you need it, or what you use case?

maybe you need `{% verbatim %}` block, that are no implemented too

**Comment by toptalo** [comment]
Hmmmm
I found some strange thing with `raw` and `verbatim` tags.

At first `{% raw %}`  tag was defined in `twig.core.js` and on commit 6aa9e97 Helder Santana has rename `{% raw %}` to `{% verbatim %}` tag. But after merge ac631f0 this change was lost and later returned in 9f0435b.

So for now, with my help there are two places where `{% verbatim %}` tag has defined: `twig.core.js` and `twig.logic.js`

Also we have `{% raw %}` tag that are outdated.

---

I think we need to revert my changes and also remove outated `{% raw %}` tag
