### ISSUE TITLE
for loop in object not working

### ISSUE THREAD

**Issue by IftekherSunny** [twigjs/twig.js#572]
```json
{ "for": "bar" }
```

for loop not working ( length = 0 )

but

```
{ 0: "bar" }
```
for loop working ( length = 1 )

why???

**Comment by IftekherSunny** [comment]
**example code:**

```twig 
 {% set var = { "foo": "bar", "foo 1": "bar 1" } %}

{% for key, value in %}
 <li> {{ value }} </li>
{% endfor %}
```

when I executed this code, the result is empty ( the 'for' loop doesn't execute ). But, the code given below shows the below result

**Code :** 
```twig 
 {% set var = { 0: "bar",  0: "bar 1" } %}

{% for key, value in %}
 <li> {{ value }} </li>
{% endfor %}
```
**Result :** 
- bar
- bar1

I don't understand, when I provide integer value as key, I get the result. But when I provide string value as key, I don't get the result.

**Comment by toptalo** [comment]
I just try this example:
```twig
{% set foo = { 0: "foo", 1: "bar" } %}
{% for key, value in foo %}
    <li> {{ value }} </li>
{% endfor %}

{% set bar = { "foo": "bar", "bar": "baz" } %}
{% for key, value in bar %}
    <li> {{ value }} </li>
{% endfor %}
```
and got this result:
* foo
* bar
* bar
* baz

Everything seems to work

**Comment by IftekherSunny** [comment]
seems worried. why not working for me :(

**Comment by toptalo** [comment]
Can you copy-paste code snippet and describe your use case. Maybe you use some plugins (gulp, grunt, other)?

**Comment by IftekherSunny** [comment]
thanks got my problem

I made a twig function that was actually return object. 

```
Twig.extendFunction('fieldsByNameIndex', function (fieldsGroup, index) {
  let results = [];
  let data = fieldsGroup[index];

  for (let i = 0; i < data.length; i++) { 
    let field = data[i];
    results[field.name] = field; // update integer value as key to field name ( string as index )
  }

  return results;
});
```

when I use this filter 

```

**Comment by toptalo** [comment]
I think it because in js array keys may be only integer numbers
