### ISSUE TITLE
Cannot set multiple variables in a single statement.

### ISSUE THREAD

**Issue by malabya** [twigjs/twig.js#576]
In PHP Twig, we can set multiple variables in a single statement. 

```
{% set foo, bar = 'foo', 'bar' %}
```
which is equivalent to
```
{% set foo = 'foo' %}
{% set bar = 'bar' %}
```

I tried the same thing in `twigjs`, but it doesn't set the variables. All the variables comes out empty.

Am I missing somthing to implement this?

**Comment by willrowe** [comment]
- Reference in [TwigPHP docs](https://twig.symfony.com/doc/3.x/tags/set.html)
- [TwigPHP example](https://twigfiddle.com/48gact)
- [twig.js example](https://codepen.io/willrowe/pen/OJvxwzw)

**Comment by willrowe** [comment]
Duplicate of #115.
