### ISSUE TITLE
Option to throw error on unbound variable

### ISSUE THREAD

**Issue by bpolaszek** [twigjs/twig.js#581]
Hello there,

Is there an option for TwigJS to say "if a variable has not been bound, throw an error"?

Currently:
```javascript
var template = twig({
    data: 'The {{ baked_good }} is a lie.'
});

console.log(
    template.render({})
);
```
Will output "The is a lie."

Despite in PHP:
```php
$twig->createTemplate( 'The {{ baked_good }} is a lie.')->render([]); 
```

will throw a `Twig_Error_Runtime` exception: _Variable "baked_good" does not exist_.

Because of that, my template renders on JS but not on PHP. 

Thank you,
Ben

**Comment by tominek** [comment]
Hello,

I also encountered this issue, but then I thought about it more and in this case, it is a valid concern, but when you introduce conditions to the template, you end up in a state where not all variables are mandatory to render the template in the end.

Example is better than 1000 words :-)

`
const template = twig({
    data: '{% if customer_name %} Hello {{ customer_name }} ! {% else %} Hello customer ! {% endif %}'
})
`

In this case it would be valid even if you don't provide **customer_name**. I guess you would need some post-compiling logic to solve this kind of issue. Which actually shouldn't be so hard to do with some simple regular expression :-)

**Comment by ericmorand** [comment]
No it wouldn't necessary be valid in Twig.

Twig specs says that your template would throw an error if `strict_variables` option is set to true.

There is a difference in Twig between being defined and being truthy. Your code test that `customer_name` is truthy, not that it is defined. For that, Twig implements the `defined` test.

What twig.js doesn't implement is the `strict_variables` option. Which means that for twig.js, your template would render the same with either `customer_name` set to `false`, an empty string or undefined.

In Twig, when `strict_variables` is set to true, the latter case would throw an error.

**Comment by willrowe** [comment]
As far as I know `strict_variables` is supported, it's just not enabled by default.

**Comment by ericmorand** [comment]
Yes, it seems you are right. It is explicitly passed to twig in one of this wiki examples:

https://github.com/twigjs/twig.js/wiki

**Comment by tominek** [comment]
You're right @ericmorand :-) Thanks @willrowe I haven't found this option.
