### ISSUE TITLE
Make a Release

### ISSUE THREAD

**Issue by RobLoach** [twigjs/twig.js#582]
There are some fixed bugs in `master` that would be great to get out as a release.

**Comment by dave-irvine** [comment]
@RobLoach I've added you as a collaborator.

**Comment by RobLoach** [comment]
Thanks @dave-irvine! I'm more than happy to get this out after we touch up a few things. Could you also add  me on https://www.npmjs.com/package/twig ?

THANKS SO MUCH! :heart:

**Comment by dave-irvine** [comment]
@RobLoach what's your npm username?

**Comment by RobLoach** [comment]
@dave-irvine `RobLoach`, or `robloach`

**Comment by dave-irvine** [comment]
@RobLoach done

**Comment by ollien** [comment]
Should this issue be closed? No release has been made

**Comment by RobLoach** [comment]
Will have some time tomorrow for this.

**Comment by ollien** [comment]
Bump. Any update?

**Comment by RobLoach** [comment]
Unfortunately "tomorrow" ended up not happening. Hopefully next week! In the mean time, feel free to use `"twig": "RobLoach/twig.js#compile"` in your package.json for the latest master.

**Comment by esbenjuul** [comment]
What can we do to make this release happen?

**Comment by dave-irvine** [comment]
@esbenjuul basically we need to solve the problems in https://github.com/twigjs/twig.js/issues/569 so that it can all be done automatically. At the moment its a pain point to make a new release which is why it happens rarely.

**Comment by RobLoach** [comment]
Ran through it manually for now:
- https://github.com/twigjs/twig.js/releases/tag/v1.13.0
- https://www.npmjs.com/package/twig

**Comment by RobLoach** [comment]
Let's consider automated afterwards https://github.com/twigjs/twig.js/issues/569
