### ISSUE TITLE
Is it possible to manipulate views with POST vars?

### ISSUE THREAD

**Issue by langy** [twigjs/twig.js#583]
Long time user, first time poster. Less of an issue, more of a query. I've Googled and gotten nowhere, asked a maintainer, and decided to just ask here. Apologies if this isn't the place, but hey, it's a Friday, so maybe I'll be forgiven / given the time of day.

I'd like to manipulate one of my views so that different data is shown based on what's POSTed from a form on a previous view. Does anyone know of a way to do this?

Pseudo code example:

[view: colour_options.twig]
```
<form action="theme.html">
<fieldset>
<label for="red">
<option name="colour" value="red" id="red"> Red
</label>
<label for="yellow">
<option name="colour" value="yellow" id="yellow"> Yellow
</label>
<label for="blue">
<option name="colour" value="blue" id="blue"> Blue
</label>
</fieldset>
<button>View theme</button>
</form>
```

[view: theme.twig, rendered as theme.html?colour=red]
```
{% set theme_colour = POST.colour; %}
<div style="background-color: {{ theme_colour }};"></div>
```

Any advice on how to achieve this would be appreciated, even if it can't be achieved with Twig.js and requires another lib.

Many thanks

**Comment by dave-irvine** [comment]
I'm guessing you mean when using Twig.js as a backend? i.e via Express?

**Comment by langy** [comment]
Yeah, via Gulp.

**Comment by dave-irvine** [comment]
So you must have a route the render?

```
app.post('/theme.html', function(req, res) {
  const theme_colour = req.body.theme_colour; // https://expressjs.com/en/api.html#req.body
  res.render('theme.twig', {
    theme_colour,
  });
});
```

**Comment by langy** [comment]
Well, the views are already rendered into html files before the POST happens... So no, I guess it's not used as a back-end. I'm just POSTing between static files. I just wondered if there was a way of being able to pass the potential POST options through into the next view, and then only show the relevant content based on the POST data.

**Comment by langy** [comment]
I've decided that the way I'm using Twig.js (as an NPM package / node module in conjunction with Gulp to render out static html files) isn't going to provide what I need. Will probably need to do something funky with JS and window.location (as suggested by @dave-irvine in a private discussion).

Apologies for cluttering up your issues board!
