### ISSUE TITLE
Dynamic HTML

### ISSUE THREAD

**Issue by IftekherSunny** [twigjs/twig.js#590]
Is it possible to create a dynamic tag like this

```
{% set sectionID = "id='" ~ id ~ "'" %}
{% set sectionClasses = "class='" ~ classes ~ "'" %}

 {# dynamic tag #}
 {{ "<" ~ field("html_tag") ~ " " ~ sectionID ~ " " ~ sectionClasses ~ " >"}}
```

**Comment by toptalo** [comment]
Hello! You can use `embed` for this case:

`customTag.twig`
```twig
<{{ tagName|default('div') }}{% if className %} class="{{ className }}"{% endif %}{% if id %} id="{{ id }}"{% endif %}>
    {% block slot %}{% endblock %}
</{{ tagName|default('div') }}>
```
Usage:
```twig
{% embed 'customTag.twig' with {
    tagName: 'section',
    className: 'section section_general',
    id: 'section_798'
} %}
    {% block slot %}
        Hello, world!
    {% endblock %}
{% endembed %}
```

Live example https://twigfiddle.com/q1i58k

**Comment by IftekherSunny** [comment]
tried this way. but not working

```
<div id="{{ id }}" class="{{ classes }}" {% if animationEnabled is defined and animationEnabled %} qx-scrollspy="{{ animation }}" {% endif %}>

**Comment by toptalo** [comment]
Hmmm. I try this example in my project with last Twig.js and it works fine.
Which version of Twig.js do you use and can you publish your case to twigfiddle?

**Comment by IftekherSunny** [comment]
twig 1.* version. ok sharing my code with you

**Comment by IftekherSunny** [comment]
@toptalo working fine on twigfiddle :o Can't figure it out, why it doesn't work on my project

**Comment by toptalo** [comment]
is your twig is 1.12.0?

**Comment by IftekherSunny** [comment]
yeah

**Comment by toptalo** [comment]
hmmm. show me your code =)

**Comment by IftekherSunny** [comment]
https://twigfiddle.com/q1i58k/2 works fine. But on my project I'm getting this

```
"<section   id="section_1" >"

    content ...

</section>
```

**Comment by toptalo** [comment]
First line in quotes?

**Comment by IftekherSunny** [comment]
yes

**Comment by IftekherSunny** [comment]
http://take.ms/wRKzt how twigfiddle shows twig version 2.X?? ` twigjs ` latest version is 1.12.0 ( thinking )

**Comment by toptalo** [comment]
Its on php Twig
Maybe some previous context can affect to result?

**Comment by IftekherSunny** [comment]
I've to check.

**Comment by toptalo** [comment]
try to console.log sectionHtml before return.

In my test output was like 
```html
 &lt;{{ tagName|default('div') }}{% if className is defined and className %} class="{{ className }}"{% endif %}{% if id is defined and id %} id="{{ id }}"{% endif %}&gt;
    {% block slot %}{% endblock %}
    <!--{{ tagName|default('div') }}-->
```
I think it because content of #section-template is invalid HTML 

try to use `jQuery("#section-template").text();`

**Comment by IftekherSunny** [comment]
` jQuery("#section-template").text(); `only pick text. but in my section-template has html mark. It doesn't work for me :(

**Comment by toptalo** [comment]
I think, If you will use script tag as template holder, then method .text() will return raw content as you expected
