### ISSUE TITLE
ES Module global works in .min.js but not .js output

### ISSUE THREAD

**Issue by btopro** [twigjs/twig.js#591]
this works when using a `<script type="module" src="hello-world.js">` style inclusion in web of the library.

`import 'twig';` - resolves to twig/twig.js, complains that Twig object is not exported to global

`import 'twig/twig.min.js';` - directly though works as it has a global scope for Twig object

??? not following the difference between these.

**Comment by willrowe** [comment]
This project is not currently compatible with ES modules. It can only be included as a full library when used in the browser. A future version will most likely move everything to modules.
