### ISSUE TITLE
Provide un-minified sources in the npm package

### ISSUE THREAD

**Issue by dimd13** [twigjs/twig.js#594]
When I write code, I, like many others, have a habit of looking into the source code of a module to see how it works, what arguments it takes, and so on. But the source code (twig.js file) in the package from NPM is minified, which makes it very difficult to read. Please fix it

**Comment by dave-irvine** [comment]
Thanks for the suggestion @dimd13, I'm looking forward to your pull request :)

**Comment by toptalo** [comment]
We can close this issue

**Comment by RobLoach** [comment]
Thanks @toptalo !
