### ISSUE TITLE
template from string

### ISSUE THREAD

**Issue by fiveandnine** [twigjs/twig.js#596]
how can i render template from string and then render the result into html, the string includes extends and block? i want to realize it in egg and koa

**Comment by ericmorand** [comment]
Are you talking about this function?

https://twig.symfony.com/doc/2.x/functions/template_from_string.html

**Comment by RobLoach** [comment]
[jstransformer-twig](https://github.com/jstransformers/jstransformer-twig) will do it. See the source there.
