### ISSUE TITLE
Most of the Twig.filters-functions crashes if you pass an undefined value to them.

### ISSUE THREAD

**Issue by m-abs** [twigjs/twig.js#60]
I discovered this by accident (misspelled a var-name).  :)

But if you pass a undefined value to the "escape"/"e" filter twig.js crashes, because the  function assumes the value is a string and just calls .replace(...) on the value.

From what I can see most of the filters will have this problem. 

I can easily fix most of the filter functions so they handle an undefined value, but I'm confused about how best to handle those that don't return a string, like "reverse", "sort", "key", "join" and "merge".

**Comment by willrowe** [comment]
I'm closing this since it is so old. If there are still outstanding issues with filters not validating their arguments correctly, please open a new issue.
