### ISSUE TITLE
[QUESTION] How do I merge 2 twig templates

### ISSUE THREAD

**Issue by ddimitrioglo** [twigjs/twig.js#607]
Is there a possibility or workaround how to merge 2 twig templates? (NOT `render`!)

To give more context, let's assume I have `base.twig`:

    <!DOCTYPE html>
    <html>
    <head>
        <title>{{ title }}</title>
    </head>
    <body>
        <div id="content">{% block content %}{% endblock %}</div>
    </body>
    </html>

and a child `content.twig`:

    {% extends "base.twig" %}
    
    {% block content %}
        <h1>Hello {{ username }}</h1>
    {% endblock %}

**Expected result:**

    <!DOCTYPE html>
    <html>
    <head>
        <title>{{ title }}</title>
    </head>
    <body>
        <div id="content">
            <h1>Hello {{ username }}</h1>
        </div>
    </body>
    </html>

**Comment by ddimitrioglo** [comment]
Any updates here?

**Comment by willrowe** [comment]
This is an interesting question. I the past, I have had the need to collapse a template into one file so that I didn't need to include all the other templates that it relied upon as well. Unfortunately, I wasn't able to come up with anything satisfactory.

**Comment by owzim** [comment]
I think this should be closed, since this not a feature supported by Twig PHP either.

**Comment by ddimitrioglo** [comment]
@owzim it's a question not a feature request, but if nobody can help then I agree that this should be marked as `unresolvable` (or smth like this) and be closed.
