### ISSUE TITLE
Namespace syntax parity with twig PHP

### ISSUE THREAD

**Issue by axten** [twigjs/twig.js#623]
It would be great to have syntax parity with twig PHP when using namespaces: 

```
// twig JS 
{{ include('my_namespace::sidebar.twig') }}

// twig PHP
{{ include('@my_namespace/sidebar.twig') }}
```

this could be achieved with a config flag, to avoid breaking change here, e.g.
`phpStyleNamespaces: true`

**Comment by RobLoach** [comment]
It should support both, without needing a config option...

https://github.com/twigjs/twig.js/blob/946da8c05248714fec15c864f5a3d013e4130652/test/test.namespaces.js#L5
https://github.com/twigjs/twig.js/blob/946da8c05248714fec15c864f5a3d013e4130652/test/test.namespaces.js#L37

What error are you getting?

**Comment by axten** [comment]
oh so it's already working... great!
Can confirm it's working.
So maybe the only task left here is to mention that in the wiki docs :)

**Comment by RobLoach** [comment]
Updated at https://github.com/twigjs/twig.js/wiki#namespaces ... Thanks!

**Comment by axten** [comment]
great!
