### ISSUE TITLE
Add Polypik as a Contributor

### ISSUE THREAD

**Issue by RobLoach** [twigjs/twig.js#627]
@PolyPik has made some good contributions lately. Would love for him to be added as a contributor!

**Comment by PolyPik** [comment]
@dave-irvine You are the only member of the twigjs organization. I request that you add me to the organization as either a member or as an outsider collaborator.

**Comment by PolyPik** [comment]
You can close this now, I got the membership.

**Comment by RobLoach** [comment]
Thanks @dave-irvine! :rocket:
