### ISSUE TITLE
Adding prefix to a dynamic tag

### ISSUE THREAD

**Issue by hamadgondal** [twigjs/twig.js#634]
I need some help with the following implementation. I wanted to add a prefix to my dynamic tag and then want twig to fetch the value for this tag.

{% set additionalServices = 'text.journey_service_'~ data.additionalServices.serviceName  %}
 
 {{ additionalServices }}

--------- Actual output ---------
text.journey_service_SMALL_PET

--------- Expected output ---------
{{ text.journey_service_SMALL_PET }}  = >  Dog

**Comment by PolyPik** [comment]
Is that even possible in PHP Twig? As far as I know there is no function in PHP Twig that takes a string argument and evaluate it to a context variable value. If this feature isn't available in PHP Twig, then it is unlikely to be in twig.js.

**Comment by ericmorand** [comment]
This is not supported by Twig, as a language. So neither in twig.js nor in TwigPHP.

However, the `_context` variable holds a reference to the context and can be used to provide what you need:

```
{% set a = 'foo' %}

{{ _context[a] }}
```

**Comment by hamadgondal** [comment]
@ericmorand thank you for the help. 

I have managed to do it in the following way and it works fine.
`{{ attribute(text, 'journey_service_'~ data.addServ.serviceName) }}`
