### ISSUE TITLE
Add function on the fly (after new twig object)

### ISSUE THREAD

**Issue by leiha** [twigjs/twig.js#64]
Hi, i found your job really usefull for me ty for that ;)

but i would like do something like this :

var template = twig({
    data: "{{ field('azerty') }}"
});

template.extendFunction("field", function(name) {
    return(name);
});

but exactly like this it's not possible.
Have u an another solution for assign a new function to only one instance for a temporary need

ty ^^

**Comment by thetiby** [comment]
@dave-irvine hi there, is the above supposed to still work? (https://github.com/twigjs/twig.js/issues/64#issuecomment-14145000) I have latest release, but when I pass a function to `render`, it doesn't work anymore (I am getting `undefined`); if I pass any other data (a number, string or boolean), it works

**Comment by willrowe** [comment]
Passing a function into the template as mentioned in [this comment](https://github.com/twigjs/twig.js/issues/64#issuecomment-14145000) is the recommended way to accomplish this.

Adding the ability to make functions available to only specific templates is not possible in TwigPHP and will not be added.
