### ISSUE TITLE
Please explain the internal logic behind twigjs.

### ISSUE THREAD

**Issue by PolyPik** [twigjs/twig.js#644]
I have already contacted @justjohn about this but since I worry that he might not respond, I decided to make an issue about this.

Twig PHP has a [documentation page](https://twig.symfony.com/doc/2.x/internals.html) outlining how its internals work. Unfortunately, we don't have a similar piece of documentation to provide an easily digestible explanation as to how the implementation of this library works.

From what I can gather from the code, the process of turning a template source file into a template object is almost completely different from that of Twig PHP aside from both having a step that involves turning the source into tokens.

Twig PHP turns the source into tokens. The tokens are used to build an Abstract Syntax Tree (AST). The AST is then used to generate PHP code that would be executed later to produced the final output when the template actually needs to be rendered.

This library involves turning the source into tokens, then those tokens are transformed into a different set of advanced tokens (note there is no AST involved), and finally those advanced tokens are later parsed into the final output when the template actually needs to be rendered.

Can anyone here explain why there seems to be such a big difference design-wise between the PHP implementation and this implementation?

**Comment by willrowe** [comment]
I assume that the difference is mostly due to JavaScript working differently than PHP. When this library was originally created, they decided to go that route. In order to fix some bugs it will need to be changed to be closer to the PHP implementation.

As I mentioned elsewhere, I'm working on implementing a new parser that is based more closely on the PHP implementation and will fix some of the inconsistencies.

**Comment by PolyPik** [comment]
> As I mentioned elsewhere, I'm working on implementing a new parser that is based more closely on the PHP implementation and will fix some of the inconsistencies.

I hope it wouldn't warrant a bump in the major version number.

**Comment by willrowe** [comment]
I'm not quite sure yet whether it would, if I have time to finish it up before v2.0.0 that would be optimal though.

**Comment by PolyPik** [comment]
Don't sweat it. The work v2.0.0 isn't exactly hurrying along right now. So far the only issue assigned under the 2.0.0 milestone is #646, which is a proposal to change the API.

**Comment by connorhu** [comment]
Some years ago i've started to work on a port with less backward compatiblity on the API layer. If the internals goes on that way (more cutting edge with classes, async/awaits, import module loading) i could help on the porting.

lexer: https://github.com/connorhu/twig.js/blob/master/src/Twig/Lexer.js
environment: https://github.com/connorhu/twig.js/blob/master/src/Twig/Environment.js

**Comment by willrowe** [comment]
Interesting, that's pretty much what I have at this point as well.

**Comment by PolyPik** [comment]
@willrowe Could you tell me which branch in your fork contains your parser work.

**Comment by willrowe** [comment]
I don't have it pushed anywhere yet. I'll open a WIP PR once it's functional enough.

**Comment by ericmorand** [comment]
I'm currently working on rewriting Twing lexer because the current one, based on TwigPHP code base, is lossy. I plan on making it a separate project (and then a separate npm module), so maybe it could be reused by twig.js?

It's written in Typescript, comes with a token stream implementation, 100% code coverage and is guaranteed to be lossless - i.e. the original source code can be perfectly recreated from the Concrete Syntax Tree.

**Comment by willrowe** [comment]
What do you mean by 'lossless'?

**Comment by ericmorand** [comment]
It's a one-to-one mapping from the grammar to a token tree. For example, whitespaces are exported to the tree:

`{{ foo }}`

Would be exported as:

`
Token(type: 'VAR_START', content: '{{')
Token(type: 'WHITESPACE', content: ' ')
Token(type: 'NAME', content: 'foo')
Token(type: 'WHITESPACE', content: ' ')
Token(type: 'VAR_END', content: '}}')
`

(types are just there for illustration, I still have to settle on their names.)

This is what makes the source code reconstructable from the tree. Nothing is lost. Comments, verbatims, whitespace control modifiers...everything is in th CST even if they are not needed by the parser - for example, comments are totally skipped by the parser.

**Comment by willrowe** [comment]
That's very interesting. I'm trying to match the PHP version of Twig as closely as possible though.

I'd rather keep the parser bundled into this library for right now, but please let us know when you have finished the lexer so we can take a look.

**Comment by ericmorand** [comment]
Actually, the lexer is heavily based on th PHP one. It's basically the lexer of Twing with sugar-coating to ensure that the original source code can be reconstucted and some other refinements to make the parser life easier - like detecting properties upstream (and handling this issue way better than what is currently done by TwigPHP and Twing: https://github.com/twigphp/Twig/issues/3041).

I'll keep you posted when it's done.

**Comment by PolyPik** [comment]
How big is this lexer by itself?

**Comment by ericmorand** [comment]
In term of number of lines?

**Comment by PolyPik** [comment]
In terms of total file size.

**Comment by ericmorand** [comment]
twig-lexer is now available:

https://www.npmjs.com/package/twig-lexer

I'm not sure about the size. The build result is around 20KB, non-minified. Not sure how much it would take once minified and uglified.

If you feel like using it, don't hesitate to bring some feedbacks. The API is not frozen yet to give people a chance to provide some feedback about it.

**Comment by PolyPik** [comment]
According to [bundlephobia](https://bundlephobia.com/result?p=twig-lexer@0.1.2) after minification and zipping, it is 3 KB.

**Comment by ericmorand** [comment]
I didn't know about bundlephobia, it's amazing! It can even identify tree-shakeable packages.
