### ISSUE TITLE
Does twig.loader.ajax.js have plans to supplement the params.async content logic?

### ISSUE THREAD

**Issue by aikefang** [twigjs/twig.js#654]
twig.js/src/twig.loader.ajax.js 
```
if (params.async) {
    // TODO: return deferred promise
    return true;
}
```
This part of the code can not be combined with async, await.

**Comment by willrowe** [comment]
The library will eventually be switched to being async only.

**Comment by aikefang** [comment]
Do you have an approximate time node?

**Comment by willrowe** [comment]
Not at this time.
