### ISSUE TITLE
Should return a deferred object when fetching template asynchronously

### ISSUE THREAD

**Issue by mattkahl** [twigjs/twig.js#66]
Not sure what the timeline for this is or if it's worthy of an issue at the present moment.

But, it looks like it was thought of at some point:

```
        if (async === false) {
            return template;
        } else {
            // placeholder for now, should eventually return a deferred object.
            return true;
        }
```

The deferred object would make rendering logic a lot more readable in frameworks like Backbone.js.

**Comment by willrowe** [comment]
Templates can now be rendered asynchronously and return a promise.
