### ISSUE TITLE
Backslashes escaping

### ISSUE THREAD

**Issue by lordaplala** [twigjs/twig.js#662]
Hello,

`<p>{{ 'test q\'uote' }}</p>`

Will result in : 

`<p>test q'uote</p>`

That's ok.

But

`{% include '@blocks/example.twig' with {
     'items' : [
          {
               'property': 'test q\'uote'
          }
     ]
 } %}`

example.twig : `<p>{{ items.0.property}}</p>`

Will result in : 

`<p>test q\'uote</p>`

Node version: 10.15.1
twigjs version: 1.13.3

**Comment by toptalo** [comment]
Just now have tried your example in my environment and its works correctly

**Comment by lordaplala** [comment]
I just tried my example in the same environement and it now works correctly. This is weird. You may close this issue then. Sorry for disturbing.

**Comment by RobLoach** [comment]
Thanks for the clear testing.
