### ISSUE TITLE
Symbol.iterator not taken into account

### ISSUE THREAD

**Issue by twifty** [twigjs/twig.js#676]
When trying to iterate an es6 class which implements a `Symbol.Iterator` method, the twig 'for in' loop actually iterates the object properties rather than invoking the iterator.

```es6
class test {
  constructor () {
    this.__children = ["a", "b", "c"]
  }
  [Symbol.iterator] () {
    var index = -1;
    return {
      next: () => ({ value: this.__children[++index], done: !(index in this.__children) })
    };
  }
}
```
```twig
{% for child in test %}
{{ child }}
{% endfor %}
```
It will print the single value '3' (length of children array)

**Comment by willrowe** [comment]
This project does not currently support looping over more complex data structures. Similar to #427.
