### ISSUE TITLE
fs.loader does not use base param

### ISSUE THREAD

**Issue by lvl99** [twigjs/twig.js#678]
I was trying to figure out why the base param is not working. Seems because the `fs` loader doesn't actually use it!

https://github.com/twigjs/twig.js/blob/master/src/twig.loader.fs.js

**Comment by lvl99** [comment]
After looking into this more, it seems to not respect the `base` param when the file has been `{% include %}` and `allowInlineIncludes` is enabled.

**Comment by willrowe** [comment]
Closing due to lack of a clear explanation of the issue. Please re-open and include more details if this is still an issue.
