### ISSUE TITLE
How to get multiple instances of Twig?

### ISSUE THREAD

**Issue by jeanfredrik** [twigjs/twig.js#683]
How do I get multiple instances of Twig so I can call `extendFilter` etc on them separately? I need this to be able to write tests for a custom Twig extension that I am working with. Example that I have tried:

```js
import Twig from 'twig';

let twig = new Twig();
twig.extendFilter('myFirstFilter', (...) => (...))

// ...

twig = new Twig(); // I want a new Twig instance without extensions
twig.extendFilter('mySecondFilter', (...) => (...))
```

**Comment by willrowe** [comment]
You can use the `Twig.factory` function.

```js
let twig = Twig.factory();
```

**Comment by jeanfredrik** [comment]
Ah, yes, that worked. Thank you!
