### ISSUE TITLE
`try catch` does not catch error on `Twig.twig()`

### ISSUE THREAD

**Issue by MickL** [twigjs/twig.js#686]
I am unable to handle errors in `Twig.twig()`:

```
    try {
      twigTemplate = Twig.twig({
        data: '{% if %}',
      });
    } catch (e) {
      console.log('error ', e);
    }
```

This throws the error anyway. Catch-block is never executed.

Environment is Node.js

**Comment by toptalo** [comment]
Try to set option `rethrow` to `true`

**Comment by MickL** [comment]
Where would I set that? Unfortunately the he documentation does not contain a full list of functions and their parameters and there is are TypeScript interfaces defined.

**Comment by toptalo** [comment]
```
try {
      twigTemplate = Twig.twig({
        rethrow: true,
        data: '{% if %}',
      });
    } catch (e) {
      console.log('error ', e);
    }
```

Sorry, this is all that I can help you.

**Comment by MickL** [comment]
That is working thank you :) What does this `rethrow` option do?
