### ISSUE TITLE
spaceless in text file with LF-only EOL prints out [object Object]

### ISSUE THREAD

**Issue by dfinton** [twigjs/twig.js#689]
In a twig file containing CRLFs at the end of lines, the `{% spaceless %}...{% endspaceless %}` tags work as expected. In text files containing LF (no carriage return) only, the following output is observed:

```[object Object]```

**Expected behavior:** spaceless removes spaces regardless of the style of line feed in a text file
**Actual behavior:** spaceless adds the text `[object Object]` in the twig output text

Node version: 12.13.1
Twigjs version: 1.14.0

This is occurring under Linux.

**Comment by maxhelias** [comment]
Should be fixed by #690 with string escape and #702 without string escape

**Comment by willrowe** [comment]
Closing due to @maxhelias comment. If this is still not working correctly, please re-open and provide an example of it working in TwigPHP via Twigfiddle and it not working in twig.js using [this template](https://codepen.io/pen?template=LYQawea).
