### ISSUE TITLE
Twig js function

### ISSUE THREAD

**Issue by yo-png** [twigjs/twig.js#718]
Hey, 
i'm using twig js template for node js 13.6.0 with express 3

I used before twig php and since i passed on twig js i'm searching how to create a function that i can use inside my twig code in php it was :

`$twig->addFunction(new Twig_SimpleFunction("name", function(){//code}));`

Do someone know how to create a twig js function??

**Comment by RobLoach** [comment]
``` js
twig.extendFunction("name", function() {
  // Stuff
});

**Comment by RobLoach** [comment]
https://github.com/twigjs/twig.js/wiki/Extending-twig.js

**Comment by yo-png** [comment]
Thanks a lot !!
