### ISSUE TITLE
Get cookies with twig js

### ISSUE THREAD

**Issue by yo-png** [twigjs/twig.js#721]
Hi,
I'm using twigjs on nodejs with express js 
I need to get all the cookies of the page with a twig funtion:
```javascript
//create twig functions
Twig.extendFunction("$_COOKIE", function(cookie) {
    // Stuff
});
```

But i don't know where to place it in my code because i need to get **req** parameter to get cookies:
`req.cookies[cookie]`

And i want for twig to access to this function on every template that i load in this code.

Thanks

**Comment by RobLoach** [comment]
`document.cookie`?

**Comment by RobLoach** [comment]
``` js
Twig.extendFunction("cookie", function(name) {
  let cookies = Object.fromEntries(document.cookie.split('; ').map(x => x.split('=')));
  return cookies[name]
})
```

```twig
{{ cookie('mycookie') }}
```

**Comment by yo-png** [comment]
but if i added the httpOnly parameter to true when initializing the cookie?? 
I really need to set the httpOnly to true so that client cannot access to it with js.
It's a really important cookie and i don't want to let the user touch to it

**Comment by RobLoach** [comment]
Users will always have access to change their own cookies. You could encrypt it, but there's only so much you can do for user cookies. Can I close this issue?

**Comment by yo-png** [comment]
Yes, i will close this issue. I found a simple way to access to users cookies on express:
```
app.use((req, res, next)=>{
  res.locals.cookies = req.cookies
  next()
})
```
and then i just access it with `cookies` in my twig template.
Hope that it can help someone
