### ISSUE TITLE
multiple macro calls leading to wrong output since v1.14.0

### ISSUE THREAD

**Issue by Baloobear** [twigjs/twig.js#727]
Hi,

when I define a macro in my twig template (incl. "_self" import) the first call of the macro will be fine. But starting with the second call the macro returns the value of the last parameter.

Example:

```
{% macro menuItem(text, class, url, isCurrent = false) %}
    <li><a href="#">dummy</a></li>
{% endmacro %}
{% import _self as menu %}

<nav>
    <ul class="menu">
        {{ menu.menuItem('Homepage', 'homepage', 'index.html', true) }}
        {{ menu.menuItem('Concept', 'concept', 'conzept.html', false) }}
        {{ menu.menuItem('About us', 'about-us', 'about-us.html') }}
    </ul>
</nav>
```

The first call will do a correct output of
`<li><a href="#">dummy</a></li>`

The second call will output `false` and the third call will output `about-us.html`.

_Note: before version 1.14.0 the output was correct._

**Comment by edosrecki** [comment]
I experience same issues.

**Comment by julmot** [comment]
Same issue here.... How to workaround this?
