### ISSUE TITLE
Version 1.15 not backwards compatible with version 1.14 and older

### ISSUE THREAD

**Issue by jbaron-gingco** [twigjs/twig.js#728]
1.15 needs a newer node (`>=8.16`) version than 1.14 (`>=6.0`).

This breaks a package depending on this one for me, because I have Node `8.10` (Default on Ubuntu 18.04 LTS) and that package specifies `"twig": "1.10.5"` as dependency.

Because of this, version 1.15 actually should be a version 2.0.0.

**Comment by willrowe** [comment]
Unfortunately, there were several breaking changes that should have been tagged as v2.0.0. This did not happen though, so there isn't much that can be done at this point. There shouldn't be any more breaking changes before v2.0.0.
