### ISSUE TITLE
exclude fuctions, not throw error

### ISSUE THREAD

**Issue by amirhbakan** [twigjs/twig.js#739]
Hi, thanks for your good package, I need when rendering a file, just resolve the defined values and don't throw error like this: 
```foo function does not exist and is not defined in the context```
I use nodejs without the express, please tell me is there any option to prevent errors like this or a way to exclude some functions or a way to tell twig js to don't compile anything, just what you know  :))
I need to have a minifier for twig with nodejs.

**Comment by stephane-r** [comment]
Hey,

I've the same issue, i don't want if we can "override" the undefined function ? For exemple, maybe we can defined the function and return null or empty string for remove this error ?

**Comment by willrowe** [comment]
Closing due to lack of an example. If this is still an issue, please re-open and provide an example of it working in TwigPHP with [Twigfiddle](https://twigfiddle.com/) and not working in twig.js using [this template](https://codepen.io/pen?template=LYQawea).
