### ISSUE TITLE
Filter inline_css

### ISSUE THREAD

**Issue by 3dmedium** [twigjs/twig.js#749]
Hi I'm using this great Library on a bigger Project so I was missing the filter "inline_css"

For all of you, also needing this filter:
It was very Simple tanks to the [Automattic/juice ](https://github.com/Automattic/juice)library
```typescript
import juice from "juice";

Twig.extendFilter("inline_css", function (value, params) {
      let html = juice(value);
      return html;
});
```

If this should work in a browser (I render twig templates completely client side) then you should use: 
```typescript
import juice from "juice/client";
```

And you should replace some libraries juice is using in tsconfig.json:
```json
"compilerOptions": {
   "paths": {
      "stream":[
        "node_modules/stream-browserify"
      ],
      "cheerio": [
        "node_modules/cheerio-without-node-native"
      ]
   }
}
```

Due to some Bugs "cheerio-without-node-native" can only be used in version "^0.20.2" for now.
Hope this is helpful for someone.

**Comment by willrowe** [comment]
As mentioned in [the TwigPHP documentation](https://twig.symfony.com/doc/3.x/filters/inline_css.html#:~:text=The%20inline_css%20filter%20is%20part%20of%20the%20CssInlinerExtension%20which%20is%20not%20installed%20by%20default.%20Install%20it%20first%3A) this filter is not part of core Twig, but is available as an extension. For this reason, I don't think it should be included in core twig.js. It could possibly added as an external extension at some point.
