### ISSUE TITLE
Add Deno support

### ISSUE THREAD

**Issue by Amund** [twigjs/twig.js#752]
Well, could be nice.

Edit : To maybe give inspiration
https://dev.to/nebrelbug/adding-deno-support-to-the-eta-template-engine-28n7

**Comment by RobLoach** [comment]
It could likely be a Twig.js extension! For an example, check out https://github.com/kalamuna/twig-drupal-filters

**Comment by elika-filin** [comment]
it would great idea to have twig support on Deno

**Comment by devalexqt** [comment]
But it's worked already, because twig working in browser, so in dene import raw `twig.js` insted `npm install`.

**Comment by janusz-f** [comment]
Support already exists https://deno.land/x/twig
