### ISSUE TITLE
Add justafish as a maintainer!

### ISSUE THREAD

**Issue by RobLoach** [twigjs/twig.js#758]
@justafish is a wonderful person, and I think Twig.js would benefit from having her as an additional maintainer :wink: 

@dave-irvine, @justjohn, @plepe Any concerns?

Maybe that's a better question for @justafish :stuck_out_tongue_winking_eye:

**Comment by dave-irvine** [comment]
I'm happy for anyone who shows an interest and reasonable care to become a maintainer :)

**Comment by justafish** [comment]
:blush:

I'm happy to be added, but with the caveat that I don't have a tonne of time available so I won't be hugely useful - but every little helps of course :smile:

**Comment by RobLoach** [comment]
Great! Should see an invite :wink:
