### ISSUE TITLE
Twig Exception : path function does not exist

### ISSUE THREAD

**Issue by crtlf** [twigjs/twig.js#759]
I just found out that the Twig `path` function is not recognized by Twig.js

Here's the part of my template triggering the error  : 

```twig
<a href="{{ path('mypath', { slug: 'slug'}) }}">See</a>
```

The full error : 

`TwigException: path function does not exist and is not defined in the context`

---

Is the a way to make it work ?
The `extendFunction` could be the solution but I don't find a good way to generate a URL from a Symfony path in Javascript.

**Comment by ericmorand** [comment]
`path` is not a function of Twig. It is a function provided by a custom PHP extension - namely the Symfony Extension. It doesn't make any sense at the language level to have a `path` function.

**Comment by crtlf** [comment]
Ok, I mistaken the scope of this plugin and wrongly though it was part of Symfony.
Thank you for your quick answer.

**Comment by ericmorand** [comment]
Twig maintainers maintain the confusion between the language itself (Twig), the PHP implementation (Twig PHP) and the product running on Twig that they provide (Symfony). It's very difficult to distinguish the scope of these two different things. It's unfortunate but they don't plan on changing anything about that. Trust me, I tired to have that conversation with them multiple times... :D

**Comment by crtlf** [comment]
Ahah I have no doubt about it

**Comment by RobLoach** [comment]
The movement has been slow lately, but we're certainly open to changing things. You're right that there's a distinction between Twig PHP, Twig Symfony, and the Twig language. Having a `path` extension would be really nice. I suppose it depends on your application how it would build the path. Thanks!
