### ISSUE TITLE
Re-rendering a template using `{% embed %}` fails

### ISSUE THREAD

**Issue by barnslig** [twigjs/twig.js#767]
## Problem description

When using `{% embed %}`, re-rendering the template causes a `Cannot extend an inline template` error.

`allowInlineIncludes` is enabled.

## Expected behaviour

The render function can be called multiple times to re-render the template.

## Detailed bug description and possible fixes

The bug is caused by assigning the resolved template as `parentTemplate` on the first render: [twig.core.js, line 1360](https://github.com/twigjs/twig.js/blob/071be04a7f0fa31ca313a3eebce1a275f6562308/src/twig.core.js#L1360).

The second time the template is rendered, `template.parentTemplate` is already the assigned template object and could directly be used. However, `Twig.Templates.load()` is called again, this time with the object instead of the template path, returning `null`: [twig.core.js, line 1340](https://github.com/twigjs/twig.js/blob/071be04a7f0fa31ca313a3eebce1a275f6562308/src/twig.core.js#L1340). This results in an empty parentTemplate and thus a failing render.

I found two possible fixes:

1. Remove the assignment in line 1360
1. Introduce a check in line 1340 whether `template.parentTemplate` is already the resolved object

Is there any preference on one of the solutions? I am not sure which impact either of the solutions have.

## Reproducing the bug

I've created an example repository to reproduce the bug: [barnslig/twigjs-embed-rerender-bug](https://github.com/barnslig/twigjs-embed-rerender-bug)

**Comment by YoungElPaso** [comment]
I have a similar experience trying to extend in an inline template. Same error I believe.

**Comment by pjoulot** [comment]
I had a similar experience using an include. Same error as well.

**Comment by willrowe** [comment]
I have confirmed this is a bug.
Here is [a TwigFiddle](https://twigfiddle.com/mdhzi3) that demonstrates how it works in TwigPHP.
Here is what happens with twig.js: https://codepen.io/willrowe/pen/abqrZXW
