### ISSUE TITLE
Version number outdated?

### ISSUE THREAD

**Issue by BT643** [twigjs/twig.js#768]
I downloaded the [v1.15.3](https://github.com/twigjs/twig.js/tree/v1.15.3) release and did:

```
npm install
npm run build
```
Then included the twig.js file in a website to be used in the browser. When I do `alert(Twig.VERSION);` I get `1.14.0` alerted out.

Am I misunderstanding what this version is, or does it need updating somewhere?

The following code is in twig.js around line 460 so I guess it needs updating there?

```
// ## twig.factory.js
//
// This file handles creating the Twig library
module.exports = function factory() {
  var Twig = {
    VERSION: '1.14.0'
  };
```
Apologies if I'm misunderstanding! Thanks.

**Comment by willrowe** [comment]
@BT643 keeping the internal `Twig.VERSION` in sync with the npm releases is a known issue. Efforts to automate the process can be tracked on #569.
