### ISSUE TITLE
The slice filter shorthand doesn't support variables

### ISSUE THREAD

**Issue by JamesB797** [twigjs/twig.js#769]
The slice filter type regex is `regex: /^\[(\d*:\d*)\]/,` which only matches something like `[10:]` but not `[length:]`. I can just use `|slice(length)` and `|slice(0, length)` but it's a little unexpected coming from php twig.

**Comment by willrowe** [comment]
Are you referring to "As syntactic sugar, you can also use the [] notation" mentioned [in the TwigPHP docs](https://twig.symfony.com/doc/3.x/filters/slice.html)?
