### ISSUE TITLE
create_attribute() does not exist

### ISSUE THREAD

**Issue by joshwaaaah** [twigjs/twig.js#771]
Hey, really enjoying using this, so thank you.

I'm wanting to use a function that exists in Twig called `create_attribute()` but I'm not having much luck... is this something that is supported by Twig JS?

**Comment by RobLoach** [comment]
There are some functions defined in https://github.com/kalamuna/twig-drupal-filters 

Looks like it's missing create attribute tho.

**Comment by joshwaaaah** [comment]
Ah okay. Do you know if this is in the roadmap at all?

I'd be tempted to look at implementing myself but not sure where I would start to be honest! I know you can extend Twig with more functions but it doesn't look like a function that just returns a value, as it also as additional functionality like addClass etc.

**Comment by ericmorand** [comment]
`create_attribute` is not a function of Twig. It it available only from the Drupal extension.

I created a package some years ago to facilitate its implementation in twig.js or Twing:

https://www.npmjs.com/package/drupal-attribute
