### ISSUE TITLE
Review blocked user in 30 days

### ISSUE THREAD

**Issue by dave-irvine** [twigjs/twig.js#772]
Open source is a place for a community to grow, through contributions from everyone. When someone makes demands on an open source project without offering their own time and energy, it drains the system.

https://github.com/twigjs/twig.js/issues/509 has been an outstanding issue for years, I have not taken the time to fix the issue as I've moved away from Twig.js but I left some instructions for anyone else to implement a fix as a PR at their convenience.

Rather than offering to implement the fix that I suggested as a PR, a consumer of open source software decided to add further comments to an Issue report rather than using the standard +1 visibility tools.

I took a quick look through his Github history and can see no contributions to open source other than raising complains on other Repos. Rather than drain further energy I took steps to block this user from the Twig.js repo, to be reviewed in 30 days.

Someone other than me should review the block. @RobLoach @justafish

**Comment by RobLoach** [comment]
Seems appropriate. Thanks @dave-irvine.
