### ISSUE TITLE
How render files with "blocks" by predefining the block content with Twig.js?

### ISSUE THREAD

**Issue by renestalder** [twigjs/twig.js#785]
So, I stuck with this here.

For testing reasons, I want to load a twig file that contains a block, let's say, like this:

```twig
{% block content %}
  <!-- Content -->
{% endblock %}
```

I saw there is a `blocks` property on the parameter list and I tried this:

```js
const template = Twig.twig({
  href: "/components/layout/multicolumn-title-text.twig",
  async: false,
  blocks: {
    content: "Simple content for demonstration"
  }
});

template.render();
```

But that doesn't seem to work. I also didn't find a fitting test case in the TwigJS tests that would do something similar.

Does anyone have any advice for me?

ps. I also use the Webpack twig loader but found, I can probably not do that with the loader and have to do it manually with TwigJS directly.

**Comment by willrowe** [comment]
I think you may be referring to the `blocks` param on the `Template.render` method. This is an undocumented param  that is for internal use only. It can only be passed a value that was generated internally, so you cannot pass strings like you were trying.

To clarify though, there is no `blocks` param on the `Twig.twig` function, like in your example. Blocks should be contained in the templates themselves, so there is no need to pass them in as params.

Just curious, did you find it by looking through the source code, or somewhere else?

**Comment by renestalder** [comment]
@willrowe 

> Just curious, did you find it by looking through the source code, or somewhere else?

That was over a year ago, so I don't exactly know any more how I found out about it :sweat_smile:. I barely remember the use case for it: I thought I would be able to programmatically use templates that have blocks too, so I could reuse the templates I have for server-side rendering on the client-side to do some island-architecture rehydration. I must found it by searching for “blocks” in the code base and then make my own conceptional wrong conclusion out of it.

**Comment by diarcastro** [comment]
@willrowe the `params.blocks` is sent here https://github.com/twigjs/twig.js/blob/master/src/twig.core.js#L1346 I was looking for this functionality, but there is no documentation and I couldn't make it work. Any clues?
