### ISSUE TITLE
 twig.js contains a reference to the file "path".

### ISSUE THREAD

**Issue by leonardola** [twigjs/twig.js#787]
When upgrading the package @symfony/webpack-encore from  0.28.2 to 1.0.0 I get the following error:
 "./node_modules/twig/twig.js" contains a reference to the file "path". 

Apparently some shared library is used on webpack-encore 0.28.2 but on webpack-encore 1.0.0 the library is not required breaking twig.js.

**Comment by Dallas62** [comment]
Hi,
Just in case, you can import he minified version.

```js
import Twig from 'twig/twig.min';
```
Regards

**Comment by leonardola** [comment]
I do not work at the company anymore. But I'll ask someone to post more details here. It may take a while though.

**Comment by willrowe** [comment]
Ok, understood. I'll close for now, if it's still an issue for anybody, it can be re-opened.

**Comment by hoffmanmc** [comment]
Hi all, I'm encountering this issue with Encore as well:
`
Module build failed: Module not found:
"./node_modules/twig/twig.js" contains a reference to the file "path".
This file can not be found, please check it for typos or update it if the file got moved.
`

**Comment by hoffmanmc** [comment]
Looks like line 435 of the `.node_modules/twig/twig.js` file:
```
module.exports = require("path");
```

**Comment by hoffmanmc** [comment]
Sure, I'm using `@symfony/webpack-encore` version 1.8.2 with symfony, and yarn as my package manager. Let me know if there's anything more specifically you'd need to help recreate it. I can provide `my yarn.lock` file if that helps.

Here is the section of my `webpack.config.js` I added to load twig js:
````
    // Adds TwigJs loader.
    .addLoader({
      test: /\.twig$/,
      exclude: /templates/,
      use: [
        { 
          loader: "twig-loader",
          options: {},
        },
      ],
    })
````

**Comment by hoffmanmc** [comment]
Here's the `yarn.lock` file
[yarn.lock.txt](https://github.com/twigjs/twig.js/files/9698338/yarn.lock.txt)

**Comment by willrowe** [comment]
From your descriptions this seems like an issue external to twig.js. The library is built to work primarily with node, which has the `path` builtin. If you are compiling using something like webpack, you need to make sure that things like `path` are shimmed.

Overall though, I'm not sure you are using things correctly, since the `twig.js` and `twig.min.js` are already built using webpack and not meant to be imported and compiled again.

I would double-check the docs for the loader, my guess is that a different file is supposed to be imported.

**Comment by hoffmanmc** [comment]
Thanks, I'll check those things out. I noticed that TwigJs is actually working despite the error, so you're probably right about that.

**Comment by Dallas62** [comment]
Hi,

In my case, the environment is React-Native, where `path` is not built-in.
Using the minified version is OK, but probably not a stable way to handle it.

Regards

**Comment by willrowe** [comment]
@Dallas62 interesting, as far as I know this library has never been tested with React-Native, so compatibility with it would be unknown.
