### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by Bilge** [twigjs/twig.js#792]
Seems there have been no commits this year. Would you advise against adoption at this point?

**Comment by dnnsjsk** [comment]
I am still using this with Gulp and it's working without problems, I hope the project isn't dead!

**Comment by obedparla** [comment]
There isn't a better option AFAIK. The maintainer/s may be busy or not want to deal with it. It's stable for the most part and I don't think Twig PHP is changing much either.

**Comment by Bilge** [comment]
There is a [better option](https://github.com/NightlyCommit/twing).

**Comment by obedparla** [comment]
Not sure by what metrics you consider that a better option, but you're welcome to use either one 😄

**Comment by JosefBredereck** [comment]
@Bilge  the option you mentioned is archived now.

Furthermore, as there are many PRs and issues that do not get updated, the feeling of a dead project maybe occur correct.

**Comment by Bilge** [comment]
It's not archived, it's [moved](https://gitlab.com/nightlycommit/twing).

**Comment by RobLoach** [comment]
While I don't actively use the project as much anymore, I'm happy to merge pull requests. If anyone is willing to step up to help maintain, would love to add to the team :+1:

**Comment by willrowe** [comment]
This project is maintained by a couple of individuals when they have time.
