### ISSUE TITLE
Question: how about a production-version of Twig.js?

### ISSUE THREAD

**Issue by rkyoku** [twigjs/twig.js#80]
Hi,

With Handlebars, one can grab a "production only" version of Handlebars that can only execute pre-compiled templates (server-side compiled).

It would be great to have the same thing with Twig.js. That way, the lib would weigh only a few kilobytes (instead of 66kB), and we could make the client download a "package" of all the templates altogether.

It would: save bandwidth, generate far fewer HTTP requests, and more importantly greatly reduce download time (important for me because I'm creating an app designed mostly for mobiles).

If it's already there, please forgive me for my question.

Best regards,

**Comment by dcorb** [comment]
+1

**Comment by vergilius** [comment]
+1

**Comment by dave-irvine** [comment]
I've taken a look at this as it would be quite helpful for me, but I definitely don't think it is as easy as it might first appear.

**Comment by mishoo** [comment]
If anyone's still interested, I wrote a [Twig->JS compiler](https://github.com/mishoo/tweeg.js/).  Whole new project though, I learned about this one half-through.

**Comment by willrowe** [comment]
This is not planned at this time.
