### ISSUE TITLE
Concenate in import not working

### ISSUE THREAD

**Issue by mledwards** [twigjs/twig.js#806]
Hello,

Hope someone can help me with this.

This import works: `{% import "@components/hero/component.macro.twig" as componentMacro %}`

But this doesn't `{% import "@components/" ~ "hero" ~ "component.macro.twig" as componentMacro %}`

The error comes back as `Can't resolve '~'`

Does anyone know a way around this? As I need to build up dynamic imports inside a for loop.

**Comment by willrowe** [comment]
Does it work if you concatenate and set to a variable, then import the variable?

```twig
{% set import_path = "@components/" ~ "hero" ~ "component.macro.twig" %}
{% import import_path as componentMacro %}
```

**Comment by mledwards** [comment]
Hi Will. I did try that, I forgot to mention. It essentially said can't resolve import_path

**Comment by eric-schmidt** [comment]
I'm running into this same issue as well, but for Includes and Embeds as well. Even when setting a variable first, it sees as though Twig.js is not properly respecting the concatenation. I've also tried interpolation and using `|join`, all with no luck 🤔

**Comment by mledwards** [comment]
Maybe this hasn't been implemented? Feels like quite a biggie. I guess for now I'll make a big ifelse statement with all the possible options. Just means 1 manual task every time we add a new importable file.

**Comment by willrowe** [comment]
I just tested this out and basic concatenation is working fine in the import paths, so there must be something else going on here.

Please provide a https://twigfiddle.com/ example that works there, but not in twig.js so I can investigate further.

**Comment by mledwards** [comment]
Hi @willrowe. Running this line shows the file is being looked for: https://twigfiddle.com/dd2c52

Locally this says `Canot resolve "/some/file/"`

**Comment by eric-schmidt** [comment]
Unfortunately, I'm running this as a part of https://github.com/emulsify-ds/emulsify-drupal, which integrates Storybook with Drupal, so it will be tough to create a demonstration of this. There are definitely a lot of cooks in the kitchen with my implementation, so it could definitely be only tangentially related to Twig.js.

Basically, I'm having issue with concatenation not being respected in an import with a variable in the path name, e.g. `{% set link_icon_path = '@atoms/04-images/svg/' ~ link_icon ~ '.twig' %}`, where `link_icon` is being dynamically passed from another component.

**Comment by willrowe** [comment]
As I mentioned above, I tested basic concatenation and it is working. What I really need is the most simple version of this that works on TwigFiddle, but not on twig.js to rule out path, loader, or issues emanating from other packages.

If it is an issue with the variable being passed in, please construct a simple version of the template inheritance/include structure.

**Comment by mledwards** [comment]
@eric-schmidt This is interesting, we're loading TwigJS into Storybook too! The plot thickens. I'll have a dig around in Storybook, see what version of TwigJS we're loading, and get back to you @willrowe

**Comment by mledwards** [comment]
https://github.com/megahertz/twigjs-loader/issues/4 :(

**Comment by willrowe** [comment]
@mledwards thanks for looking into that. @eric-schmidt can you confirm that the referenced issue is what was causing you problem as well?

**Comment by eric-schmidt** [comment]
@willrowe Yup, that appears to be the culprit. Thanks for finding that, @mledwards 👍
