### ISSUE TITLE
Help maintaining twig.js

### ISSUE THREAD

**Issue by dnnsjrng** [twigjs/twig.js#809]
Hello @RobLoach

as discussed by mail, here is the corresponding issue. As being said, we would like to help you actively, because Twig.js is an integral part of our tech-stack at https://github.com/factorial-io and we currently can't develop without it. 

[@fynn](https://github.com/MVSde)
[@dnnsjnrg](https://github.com/dnnsjrng)

would like to help you from now on. Possibly other developers from our side, if needed.

We are looking forward to it! 🎈 🥳

**Comment by RobLoach** [comment]
Thanks a lot for jumping on board! :rocket:

**Comment by willrowe** [comment]
@dnnsjrng @fynn thanks for your offer to help. I'm starting to triage the issues and PRs and will be marking issues that will require PRs with the [`help wanted` label](https://twig.symfony.com/doc/1.x/tests/divisibleby.html). Feel free to check out those issues and comment on any that you would like to create a PR for.
