### ISSUE TITLE
Override dot accessor (e.g. user.firstName) to ignore case

### ISSUE THREAD

**Issue by tacman** [twigjs/twig.js#810]
I'm moving some templates from server-side twig to twigjs.  (twigjs rocks, by the way!)

The dot / attribute in twig ignore case and strips the 'get' when accessing a property, in part because methods aren't case-sensitive in PHP.  This allows {{ user.firstName }} and {{ user.firstname }} to be the same, but in twigjs the property name must match exactly.

Is there any way to override that behavior?

**Comment by willrowe** [comment]
What is `user` in your case? Can you provide a simple example?

**Comment by tacman** [comment]
For example, my entity has a language field call $ISO639 (the 2-letter language code).  The getter is
```
    #[ORM\Column(type: 'string', length: 2)]
    #[Groups(["subtitle.read"])]
    private $ISO639;

    public function getISO639(): ?string
    {
        return $this->ISO639;
    }
```

In my twig code, I can write 
```twig

{{ subtitle.iso639 }} or {{ subtitle.getIso639 }} or {{ subtitle.ISO639 }}
```

but in twig.js, the data pass into the template is {ISO639: 'en'}, so not surprisingly, only  {{ subtitle.ISO639 }} works.

It's not a huge deal, I can be more disciplined, or rename my fields, but the data and entities were creating automatically from a CSV file (not just this one field).

So it got me thinking that, like Symfony's accessor component, maybe there's a way to allow for case-insensitive lookups, so that either would work.

**Comment by willrowe** [comment]
At this point `twig.js` only works with basic objects, so it has no deeper understanding of classes, getters, or methods in the same way that TwipPHP supports magic getters.

Your best bet would be to format the data passed to the template in `twig.js` to match the template. For example:
```json
{
    "iso639": "en"
}
```
That way you don't have to update your templates and you get consistent output.
