### ISSUE TITLE
value attribute stripped from option elements

### ISSUE THREAD

**Issue by kmonahan** [twigjs/twig.js#819]
Seeing an odd issue where include `<option value="whatever">Some Text</option>` results in the output `<option>Some Text</option>`, with the `value` attribute stripped. Other attributes work as expected, e.g. `<option myValue="whatever">Some Text</option>` results in `<option myvalue="whatever">Some Text</option>`.  The same issue does _not_ occur with `<input>` elements, just with `<option>` elements inside a `<select>`.

**Comment by willrowe** [comment]
Can you please provide an example of it working in TwigPHP via [twigfiddle](https://twigfiddle.com/) and an example of it not working in twig.js using [this template](https://codepen.io/pen?template=LYQawea)?

**Comment by kmonahan** [comment]
Closing as I've finally chased the issue down to a different library
