### ISSUE TITLE
Filtre Trans not working

### ISSUE THREAD

**Issue by chakib-lah** [twigjs/twig.js#841]
Hello, i'm using twig.js, and i need to use translation in my twig view, but i got this message error 
message: 'Unable to find filter trans', name: 'TwigException', type: 'TwigException'

 `    <p>{{ title }}</p>
     <p>{{ 'yes' | trans({}, 'global') }}</p>`

did you have the same probleme

**Comment by willrowe** [comment]
There is no `trans` filter in Twig core, you may be referring to the one available in the [Symfony twig extension](https://symfony.com/doc/current/reference/twig_reference.html#trans). twig.js only provides core filters.

**Comment by chakib-lah** [comment]
Thank you for response
