### ISSUE TITLE
accessing an array element with a colon

### ISSUE THREAD

**Issue by tacman** [twigjs/twig.js#854]
I'm passing in a hydra json response, which includes an element with a key of 'hydra:member'.

My twig template is

```twig
<h3>
    {{ data['@type'] }}
</h3>
{% for d in data['hydra:member'] %}
{{ d.id }}
{% endfor %}
```

This throws an error

TwigException: Twig.expression.type.array.start cannot follow a Twig.expression.type.variable at template:4 near '[...'
 ERROR  Failed to compile with 1 errors                                                                                                                                                       Syntax Error: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)

My solution is to set a temporary variable and use it, but I'm wondering if there's a better way, or if this can be fixed.

```twig
{% set hack = 'hydra:member' %}
{% for d in data[hack] %}
{{ d.id }}
{% endfor %}
```

Thanks.  I think this library rocks.

**Comment by antoineveldhoven** [comment]
According to my findings it should work as expected:

[TwigJS @ Codepen](https://codepen.io/antoineveldhoven/pen/ExrxvJK)
[Twig 3.7.1 @ TWIGFiddle](https://twigfiddle.com/d8xl8k)

**Comment by tacman** [comment]
Indeed, I'm having a hard time reproducing it, or even finding where I used it in my code.  Thanks, if I find it I'll reopen.

**Comment by antoineveldhoven** [comment]
> Indeed, I'm having a hard time reproducing it, or even finding where I used it in my code. Thanks, if I find it I'll reopen.

Please reopen this issue, since I've only provided the examples.
I've submitted a PR that could fix this issue, although I'm not sure is it will break anything else.
