### ISSUE TITLE
Any way to test syntax of twig templates?

### ISSUE THREAD

**Issue by silentmantra** [twigjs/twig.js#863]
There could be a situation of some legacy code cleanup in hundreds of twigs.
After that it would be nice to test syntax of all templates.
I've tried the php twig, but `tokenize()` doesnt throw a syntax error,
other methods like `createTemplate()` require full environment recreated like functions and filters.
Is there any way to check twig template syntax with the `Twig.js`?

**Comment by willrowe** [comment]
You could take a look at the [Symfony linter](https://symfony.com/doc/current/templates.html#linting-twig-templates) and see how they're doing it under the hood.

**Comment by silentmantra** [comment]
> You could take a look at the [Symfony linter](https://symfony.com/doc/current/templates.html#linting-twig-templates) and see how they're doing it under the hood.

I've just done $twig->parse() in php.
But anyway it's interesting whether it possible with twig.js

**Comment by silentmantra** [comment]
> There's no built-in linter, but creating a new template and skipping the `render` call may do the same thing. Error handling during the template parsing isn't quite as robust as with TwigPHP, so you would need to do some testing to see if it functions as you expect.

Ok, will look at twig.js' render().
Or you could hint me

**Comment by willrowe** [comment]
I was saying there's no need to call `render`, just create the template and the parser will run.

**Comment by silentmantra** [comment]
> I was saying there's no need to call `render`, just create the template and the parser will run.

hmm, that easy? will try

**Comment by ericmorand** [comment]
You can also give [twig-lexer](https://www.npmjs.com/package/twig-lexer) a look. It is the lexer used by twing to lex a template.
