### ISSUE TITLE
Command to create an inlined version

### ISSUE THREAD

**Issue by ay13** [twigjs/twig.js#864]
The topic of inlined templates has come up a lot in the issue queue but I have not seen a simple solution. 

Is there a way to create an inlined version (with includes or embeds) that is ready to have options passed to it at a later point?

For example, if you have this twig template

**heading.twig**
```twig
<div>
  <h1>{{heading}}</h1>
  {% include "search.twig" %}
</div>
```
**search.twig**
```twig
<div>
  <input type="text" id="search" placeholder="Search">
  {% include "button.twig" %}
</div>
```
**button.twig**
```twig
<div>
  <button class="button">{{label}}</button>
</div>
```

I would like to be able to store this compiled template as a variable named `ctx`
```twig
<div>
  <h1>{{heading}}</h1>
  <div>
    <input type="text" id="search" placeholder="Search">
    <div>
      <button class="button">{{label}}</button>
    </div>
  </div>
</div>
```

Which I can later use like this
```js
Twig.twig({
  data: ctx,
}).render({
  heading: 'Site search',
  label: 'Search'
});
```

Which would render 
```HTML
<div>
  <h1>Site search</h1>
  <div>
    <input type="text" id="search" placeholder="Search">
    <button class="button">Search</button>
  </div>
</div>
```

Is something like this possible?

**Comment by willrowe** [comment]
What I have done in the past is to load the templates for the includes and embeds, which the Twig loader will store in its singleton and make available to other templates that reference them.

**Comment by ay13** [comment]
@willrowe can you point me to a code example?

Thanks!

**Comment by willrowe** [comment]
Sure, something like this should work:

```js
Twig.twig({
  allowInlineIncludes: true,
  data: `
    <div>
      <button class="button">{{label}}</button>
    </div>
  `,
  id: 'button.twig',
});
Twig.twig({
  allowInlineIncludes: true,
  data: `
     <div>
        <input type="text" id="search" placeholder="Search">
        {% include "button.twig" %}
      </div>
  `,
  id: 'search.twig',
});

Twig.twig({
  allowInlineIncludes: true,
  data: `
    <div>
      <h1>{{heading}}</h1>
      {% include "search.twig" %}
    </div>
  `,
}).render({
  heading: 'Site search',
  label: 'Search'
});
```

**Comment by ay13** [comment]
Thank you for the code example @willrowe 

I will close this issue
