### ISSUE TITLE
Include tag behavior

### ISSUE THREAD

**Issue by Geolim4** [twigjs/twig.js#875]
Hello, [following my last contribution](https://github.com/twigjs/twig.js/issues/392#issuecomment-1758428807) I was wondering how the `{% include 'xxxx' %}`  is supposed to work ?

Does it make a xhr/fetch request to retrieve the template (depending the `base` parameter, or does it just query a "register"' that contain a list of preloaded template file ?

Sorry but the documentation lack of examples et demos, I'd like some enlightenments  ;D

Thans you again.

**Comment by willrowe** [comment]
It depends on your use case. If you are trying to render templates in the browser [this might help](https://github.com/twigjs/twig.js/wiki#browser-usage).

**Comment by Geolim4** [comment]
> It depends on your use case. If you are trying to render templates in the browser [this might help](https://github.com/twigjs/twig.js/wiki#browser-usage).

Thanks I tried this wiki already, but I'm not sure if an inline template supports the include tags. I'm fetching by myself the twig template for some reason, so I'm passing it as an content  to twig lib.

**Comment by ericmorand** [comment]
> Thanks I tried this wiki already, but I'm not sure if an inline template supports the include tags.

According to the spec, it does: an inline template is no different than another type of template. Actually, there is no such thing as inline templates: there are just, well, templates.

**Comment by Geolim4** [comment]
Hmm tried `path` and `href` option, did not worked. I implemented my own "include" function with async fetch and it works fine. Thank you anyway.
