### ISSUE TITLE
Customize Loader file

### ISSUE THREAD

**Issue by piscesCat** [twigjs/twig.js#876]
I want to use Twig {{ include() }}, but CF workers don't support any interaction with FS. I want to customize Loader so that I can use CF KV as a FS, in addition to being able to use import and fetch. Do you have any solution?

**Comment by piscesCat** [comment]
The reason I want to customize the loader is to be able to replace FS into CF KV according to the model of CF workers

**Comment by piscesCat** [comment]
> There is no built-in way to do this, but you can create and register your own custom loader. Also, just a heads up, the `include` function is not supported yet, just the`include` tag.

 I hope to have this functionality soon

**Comment by piscesCat** [comment]
> @piscesCat actually, you can (as @willrowe explained): by creating and registering your own custom loader. 

Sorry but I couldn't find any documentation

**Comment by willrowe** [comment]
You can try looking at the loaders in the library for reference and copying one of them and altering for your needs.

**Comment by piscesCat** [comment]
> You can try looking at the loaders in the library for reference and copying one of them and altering for your needs.

It seems like there are too many things involved that will have to be fixed yet. I hope in your free time, you can write more documents related to custom loader on twigjs wiki. Thankyou☺️
