### ISSUE TITLE
Support async for registerLoader

### ISSUE THREAD

**Issue by piscesCat** [twigjs/twig.js#889]
My project needs to do this, because the template content needs await to load. I tried everything including .then but it still doesn't work 
 
```
Twig.extend(Twig => {
  Twig.Templates.registerLoader('customLoader', async (location, params) => {
   params.data = await example.get(location);
   params.allowInlineIncludes = true;
   const template = new Twig.Template(params);
   return template;
  });
 });
```

**Comment by willrowe** [comment]
Please reference the built-in loaders for how they handle async. Async functions and returning promises from loaders is not supported yet, but callbacks are supported.
