### ISSUE TITLE
How to render a template asynchronously?

### ISSUE THREAD

**Issue by TweCon** [twigjs/twig.js#890]
Hey,

I'm trying to have Twig.js render a template asynchronously but I can't find the correct way to achieve this. According to the ASYNC documentation, it should be as simple as executing the `renderAsync` method of the template, but it seems to render synchronously.

```js
const Twig = require("twig");

const template = Twig.twig({
    data: '{{ foo }}',
    autoescape: true
});

console.log(template.renderAsync({foo: 'bar'}));
```

Here is the output of `console.log`:
```sh
{ then: [Function (anonymous)], _value: 'bar', _state: 1 }
```

As you can see, it returns an object providing a `then` method and a `_value` property, but:

* It is definitely not a promise - there are not `catch` and `finally` methods
* The `_value` property contains the rendered template, which means that the rendering was done synchronously

Put differently, consider the following code:

```js
const Twig = require("twig");

const template = Twig.twig({
    data: `TWIG RENDER DONE`
});

template.renderAsync({foo: 'bar'}).then(console.log);
console.log('NEXT INSTRUCTION');

// let's compare with a proper asynchronous behaviour
const {createEnvironment, createArrayLoader} = require("twing");

const environment = createEnvironment(createArrayLoader({
    index: `TWING RENDER DONE`
}));

environment.render('index', {}).then(console.log);
console.log('NEXT INSTRUCTION');
```

The console output is:

```shell
TWIG RENDER DONE
NEXT INSTRUCTION
NEXT INSTRUCTION
TWING RENDER DONE
```

Twig.js is clearly not rendering asynchronously.

So, how can we render templates asynchronously with Twig.js?

**Comment by willrowe** [comment]
twig.js uses its own implementation of promises, not native promises. You can see an explanation of how it works [here](https://github.com/twigjs/twig.js/blob/master/ASYNC.md).

Since the example code you included does not do anything asynchronously, it just runs the code synchronously. If you were to actually do something asynchronous it would execute in a different order, see [this example](https://codepen.io/willrowe/pen/wvNXzYP).

**Comment by TweCon** [comment]
I understand, but isn't it a violation of the contract of the `renderAsync` method? We expect it to actually be asynchronous - that it is to let the control flow move to the next instruction as soon as it started.

Here, we can't know by advance if the method will actually let the control flow continue or if it will block it? Typically in my example the flow is blocked even though I explicitely wanted it to not be blocked.

Is there a way to guarantee that `parseAsync` is always asynchronous?

**Comment by willrowe** [comment]
I'm not sure why it was implemented in this way and am not a big fan of it myself, but that is the way that it is implemented. The only way to force it to be asynchronous would be to return a promise at some point during the rendering.
