### ISSUE TITLE
include syntax

### ISSUE THREAD

**Issue by rafipiccolo** [twigjs/twig.js#892]
With latest twig there is a new way to do includes

Before
```
{% include('template.html') with vars %}
```

After
```
{{ include('template.html', vars) }}
```

is it going to be supported ?
The ecosystem is already moving forward and now it breaks my code :)
https://github.com/VincentLanglet/Twig-CS-Fixer/issues/228

**Comment by ericmorand** [comment]
> With latest twig there is a new way to do includes

For information, this is not new. Twig team has been recommending to not use the `include` tag for years: https://twig.symfony.com/doc/3.x/tags/include.html

The `include` function has been around since 2012 or so, and the recommandation against the `include` tag since Twig 1.12 (2019 I think).

**Comment by ericmorand** [comment]
I totally agree.

**Comment by OpneSourceGame-UE5** [comment]
bonjour 
je salut tout le monde pour ce travaile voila je trouve quelque souci avec ma version de code seluit la 

**ChatGPT**

Ce script Python utilise la bibliothèque PyDrive pour interagir avec l'API Google Drive et enregistrer les données récupérées à partir du site yggtorrent.cool. Voici un résumé de ce qu'il fait :

Authentification avec Google Drive : Utilise OAuth2 pour se connecter à Google Drive via le navigateur web.
Création d'un dossier sur Google Drive : Crée un dossier nommé "yggDATA" pour stocker les données scrapées.
Enregistrement des données : Scrappe les données du site yggtorrent.cool, les formate et les enregistre dans des fichiers texte individuels.
Affichage des données : Affiche les données extraites à des fins de vérification.
Le script extrait les données de plusieurs pages du site web en suivant les liens de pagination jusqu'à atteindre le nombre maximal de pages spécifié. Une fois les données collectées, elles sont sauvegardées dans le dossier "yggDATA" sur Google Drive, chaque page de données étant enregistrée dans un fichier texte distinct. Enfin, le script affiche les données extraites pour vérification.

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# Authentification OAuth2 avec Google Drive
gauth = GoogleAuth()
gauth.LocalWebserverAuth()  # Autorisation via navigateur web
drive = GoogleDrive(gauth)

# Créer un dossier sur Google Drive pour stocker les données
def create_folder(folder_name):
    folder_metadata = {
        'title': folder_name,
        'mimeType': 'application/vnd.google-apps.folder'
    }
    folder = drive.CreateFile(folder_metadata)
    folder.Upload()
    return folder['id']

# Enregistrer les données sur Google Drive
def save_to_google_drive(all_data, folder_id):
    for i, data in enumerate(all_data):
        file_content = '\n'.join('\t'.join(item) for item in data)
        file_name = f'data_{i+1}.txt'
        file = drive.CreateFile({'title': file_name, 'parents': [{'id': folder_id}]})
        file.SetContentString(file_content)
        file.Upload()

def extract_content(html_content, content_selector):
    soup = BeautifulSoup(html_content, 'html.parser')
    content_elements = soup.select(content_selector)
    content = [element.get_text(strip=True) for element in content_elements]
    return content

def extract_lists(content, list_selector):
    lists = []
    for item in content:
        soup = BeautifulSoup(item, 'html.parser')
        list_elements = soup.select(list_selector)
        for ul in list_elements:
            items = [li.get_text(strip=True) for li in ul.find_all('li')]
            lists.append(items)
    return lists

def find_next_page(current_url, html_content, next_page_selector):
    soup = BeautifulSoup(html_content, 'html.parser')
    next_link = soup.select_one(next_page_selector)
    if next_link:
        next_page_url = urljoin(current_url, next_link['href'])
        return next_page_url
    else:
        return None

def get_all_pages_data(start_url, max_pages=3, content_selector='.table'):
    all_data = []
    current_page = 1
    current_url = start_url
    while current_page <= max_pages:
        print(f"Collecting data from page {current_page}")
        response = requests.get(current_url)
        if response.status_code == 200:
            content = extract_content(response.content, content_selector)
            page_data = extract_lists(content, 'ul')
            all_data.extend(page_data)
            next_page_url = find_next_page(current_url, response.content, '.pagination a[rel="next"]')
            if next_page_url:
                current_url = next_page_url
                current_page += 1
            else:
                break
        else:
            print(f"Failed to retrieve page {current_page}")
            break
    return all_data

# Créer un dossier yggDATA sur Google Drive
folder_name = 'yggDATA'
folder_id = create_folder(folder_name)

# Exemple d'utilisation avec un grand nombre de pages :
start_url = 'https://www.yggtorrent.cool'
max_pages = 3

# Appel de la fonction principale
all_data = get_all_pages_data(start_url, max_pages)

# Enregistrer les données sur Google Drive
save_to_google_drive(all_data, folder_id)

# Affichage des données extraites
for i, data in enumerate(all_data):
    print(f"List {i+1}:")
    for item in data:
        print(item)
    print()

**Comment by willrowe** [comment]
Duplicate of #392
